### ISSUE TITLE
Is there a method to switch to another database after instantiating the client in the Java SDK?

### ISSUE THREAD

**Issue by alpha2wang** [milvus-io/milvus-sdk-java#1003]
Is there a method to switch to another database after instantiating the client in the Java SDK?

**Comment by yhmo** [comment]
The address of the database is specified when you declaring a MilvusClient, and this address cannot be changed. If you want to connect to another database, declare a new MilvusClient by its address.

**Comment by xiaofan-luan** [comment]
> The address of the database is specified when you declaring a MilvusClient, and this address cannot be changed. If you want to connect to another database, declare a new MilvusClient by its address.

@yhmo @alpha2wang 
I think we need a "use database xxx"

**Comment by yhmo** [comment]
If the "database" is db of milvus, MilvusClientV2 has the interface [useDatabase()](https://github.com/milvus-io/milvus-sdk-java/blob/756f9561a5394d6f60dd42790793f37a47031998/src/main/java/io/milvus/v2/client/MilvusClientV2.java#L111), which can switch to another database. But the V1 MilvusClient doesn't have the ability.

But if the "database" is "another milvus instance", then you have to create another MilvusClient to connect.
