### ISSUE TITLE
how connect to a milvus cluster

### ISSUE THREAD

**Issue by hgaong** [milvus-io/milvus-sdk-java#1006]
```
ConnectConfig.builder()
    .uri(String uri)
    .token(String token)
    .build();
```

The `uri` can only correspond to one host. If the machine corresponding to the URL is down and cannot be restored, but the entire cluster is still running normally. Won't the Java program be unable to access the cluster?

**Comment by hgaong** [comment]
Isn't there a way like the Kafka Java SDK where multiple servers can be configured? Configuring only one URI might lead to a single point of failure, right?

**Comment by yhmo** [comment]
For each milvus cluster, there is a proxy node to receive requests from client. You can add more proxy nodes to a cluster. Each proxy node has its address. If one proxy node is down, the other proxy nodes still work. So, you can use N MilvusClient for N proxy nodes, each MilvusClient connects a proxy node.

If your cluster has only one proxy node(a single uri), you will not able to connect the cluster if the proxy node is down.

Java SDK can handle multiple clusters by MilvusMultiServiceClient. This ability is not described in the document since we have concerns about the consistency of clusters.
If you have multiple milvus clusters, you can use this class to interact with them:
```
ServerAddress serverAddress = ServerAddress.newBuilder().withHost("address1").withPort(port1).build();
ServerAddress serverSlaveAddress = ServerAddress.newBuilder().withHost("address2").withPort(port2).build();
MultiConnectParam connectParam =  MultiConnectParam.newBuilder().withHosts(Arrays.asList(serverAddress, serverSlaveAddress)).build();
MilvusClient client = new MilvusMultiServiceClient(connectParam);
```
All the requests created by MilvusMultiServiceClient will be sent to multiple clusters at the same time.

**Comment by hgaong** [comment]
> For each milvus cluster, there is a proxy node to receive requests from client. You can add more proxy nodes to a cluster. Each proxy node has its address. If one proxy node is down, the other proxy nodes still work. So, you can use N MilvusClient for N proxy nodes, each MilvusClient connects a proxy node.
> 
> If your cluster has only one proxy node(a single uri), you will not able to connect the cluster if the proxy node is down.
> 
> Java SDK can handle multiple clusters by MilvusMultiServiceClient. This ability is not described in the document since we have concerns about the consistency of clusters. If you have multiple milvus clusters, you can use this class to interact with them:
> 
> ```
> ServerAddress serverAddress = ServerAddress.newBuilder().withHost("address1").withPort(port1).build();
> ServerAddress serverSlaveAddress = ServerAddress.newBuilder().withHost("address2").withPort(port2).build();
> MultiConnectParam connectParam =  MultiConnectParam.newBuilder().withHosts(Arrays.asList(serverAddress, serverSlaveAddress)).build();
> MilvusClient client = new MilvusMultiServiceClient(connectParam);
> ```
> 
> All the requests created by MilvusMultiServiceClient will be sent to multiple clusters at the same time.

好嘟谢谢

**Comment by ahern88** [comment]
我使用 nginx 反向代理多个 proxy的 gRPC协议，nginx配置 keepalived 做vip漂移，这样客户端只需通过vip连接到nginx即可。感觉这样简单点，不知道这样会不会有什么风险。

**Comment by ahern88** [comment]
@yhmo 后续milvus java sdk 会出一个cluster连接的api吗，配置多个uri，本地做负载均衡和故障切换吗？

**Comment by yhmo** [comment]
@ahern88 
目前没有计划做

**Comment by hgaong** [comment]
感觉很靠谱呀，应该没啥问题



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 14, 2024 15:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [milvus-io/milvus-sdk-java] how connect to a milvus cluster(Issue #1006)




 
我使用 nginx 反向代理多个 proxy的 gRPC协议，nginx配置 keepalived 做vip漂移，这样客户端只需通过vip连接到nginx即可。感觉这样简单点，不知道这样会不会有什么风险。

**Comment by xiaofan-luan** [comment]
> @yhmo后续milvus java sdk会出一个集群连接的api吗，配置多个uri，本地做负载均衡和故障切换吗？

milvus的proxy是无状态的。因此并不需要重客户端通过链接多个地址来保证高可用。正确的方式是挂ALB或者Nginx然后起多个proxy做负载均衡
