### ISSUE TITLE
milvus2.4.5 concurrent insert error

### ISSUE THREAD

**Issue by ahern88** [milvus-io/milvus-sdk-java#1053]
I am using the Milvus SDK for Java version 2.4.2.

Insert 35,000 records of data, and there are issues with 1,500 entries. The error is as follows:

![image](https://github.com/user-attachments/assets/c619ed13-1c02-4736-b9ee-8034ae347593)

I am certain that there is no issue with the message, as I have tested each one individually without any problems.

**Comment by yhmo** [comment]
Upgrade your Java SDK to v2.4.3 which fixed a thread-safe bug:
Fix thread-safe bug of insert/upsert interfaces for MilvusClientV2


```
[milvus-sdk-java-2.4.3](https://github.com/milvus-io/milvus-sdk-java/releases/tag/v2.4.3) [Latest](https://github.com/milvus-io/milvus-sdk-java/releases/latest)

Release date: 2024-08-09

Compatible with Milvus v2.4.x

Feature
Implement database related interfaces including createDatabase/dropDatabase/alterDatabase for MilvusClientV2
Implement getServerVersion interface for MilvusClientV2
Provide client/connection pool for V1 and V2
Improvement
Implement retry machinery for MilvusClientV2
Bug
Fix thread-safe bug of insert/upsert interfaces for MilvusClientV2
Fix a bug of describeCollection that collection properties not returned for MilvusClientV2
```
