### ISSUE TITLE
索引参数丢失

### ISSUE THREAD

**Issue by itflash** [milvus-io/milvus-sdk-java#1087]
问题：V2，SDK版本：2.4.4，extraParams设置无效

![image](https://github.com/user-attachments/assets/88c1e8a1-b2ec-468d-a310-61ddaa142886)

![image](https://github.com/user-attachments/assets/c26c6e61-52de-4d43-9243-c22c66ecf34a)

期望：
![image](https://github.com/user-attachments/assets/3c8bab27-18d7-4f94-a1df-da1b9dc5f1d6)

**Comment by xiaofan-luan** [comment]
https://github.com/milvus-io/milvus/issues/36453

see here

**Comment by xiaofan-luan** [comment]
@itflash 
what is the result of describe?

**Comment by xiaofan-luan** [comment]
we want to make sure this is a java sdk bug or just a attu display issue

**Comment by itflash** [comment]
> @itflash what is the result of describe?

下面那个是用python sdk创建的，没问题；上图使用java sdk，那两个参数（M、efConstruction）没有设置成功

**Comment by xiaofan-luan** [comment]
看起来使用方式没有问题 @yhmo please help on it

**Comment by yhmo** [comment]
确实是个V2 client的bug。V1 client是好的。

**Comment by yhmo** [comment]
Fixed by this pr: https://github.com/milvus-io/milvus-sdk-java/pull/1094

**Comment by dingle66** [comment]
> 确实是个V2 client.createCollection()的bug。V1 client是好的。
> 
> 后续版本会修复这个bug。

预计啥时候修复这个问题啊，Restful的V2版本也有这个问题

**Comment by yhmo** [comment]
> > 确实是个V2 client.createCollection()的bug。V1 client是好的。
> > 后续版本会修复这个bug。
> 
> 预计啥时候修复这个问题啊，Restful的V2版本也有这个问题

上周五发布的java sdk v2.4.5已经修复了这个问题。
