### ISSUE TITLE
blockingStub.withDeadlineAfter(1, TimeUnit.SECONDS)。连接超时问题

### ISSUE THREAD

**Issue by LwengGitHub** [milvus-io/milvus-sdk-java#1103]
这个1秒能不能去掉，经常容易超时

**Comment by yhmo** [comment]
差点忘了这事了，刚提交了一个pr改掉：https://github.com/milvus-io/milvus-sdk-java/pull/1106
等[这个pr](https://github.com/milvus-io/milvus-sdk-java/pull/1099)进去之后再发一个版本，预计这两天。

**Comment by yhmo** [comment]
v2.4.6 has already been released, which fixed this issue.
