### ISSUE TITLE
No enum constant io.milvus.v2.common.ConsistencyLevel.SESSION

### ISSUE THREAD

**Issue by itflash** [milvus-io/milvus-sdk-java#1112]
sdk版本：2.4.5，v2
![image](https://github.com/user-attachments/assets/015b155f-7b3b-4d92-b3b7-ab6bd310a3b9)
![image](https://github.com/user-attachments/assets/b15eea3d-b803-47d3-835d-763f3dfc0778)
![image](https://github.com/user-attachments/assets/01c49532-4ca2-478d-97ad-693d2b3870b5)

**Comment by itflash** [comment]
@yhmo 那一致性为SESSION的collection在java怎么查询呢，查询参数为STRONG也报错

![image](https://github.com/user-attachments/assets/c3530aa1-5e4f-4386-838a-12bec9e4c5a5)

**Comment by yhmo** [comment]
Java SDK没有那个Session相应的Enum定义，而这张表的默认consistence level是Session，所以在describeCollection的时候就会报错。下个版本我加一下对Session的支持吧。目前的话你只能使用python sdk去查询这张表。

**Comment by yhmo** [comment]
Session patch:
https://github.com/milvus-io/milvus-sdk-java/pull/1130

**Comment by yhmo** [comment]
Session level is supported from v2.4.7, close this issue.
