### ISSUE TITLE
milvus-sdk-java runing

### ISSUE THREAD

**Issue by jiangchen3512** [milvus-io/milvus-sdk-java#112]
env：
jdk11 milvus_0.10.0 eclipse
operation：
1、git clone https://github.com/milvus-io/milvus-sdk-java 
2、Import maven project to eclipse 
3、maven install success
question：
some java file miss jar dependence（eg： MilvusServiceGrpc cannot be resolved to a type）
purpose：
How can I make it work？
thanks!

**Comment by sahuang** [comment]
Hi,

If you want to try Java SDK, simply add `milvus-sdk-java/examples/` to IDE and maven install. The examples pom.xml will contain milvus-java-sdk jdk and it will automatically install for you. Then you can start milvus server and run examples program.

**Comment by jiangchen3512** [comment]
thanks

**Comment by NatarajanThangaraj** [comment]
https://github.com/milvus-io/milvus-sdk-java/issues/1136#issue-2610627173
@sahuang 
Bro I need your help..
