### ISSUE TITLE
Issue encountered while running the milvus-sdk-java example.

### ISSUE THREAD

**Issue by NatarajanThangaraj** [milvus-io/milvus-sdk-java#1136]
I cloned the entire repository in Eclipse as a Maven project.
 When I tried to run the example...
![Screenshot from 2024-10-24 12-01-16](https://github.com/user-attachments/assets/a237faeb-456e-4c16-a7b0-5ada923220a1)

![Screenshot from 2024-10-24 12-01-38](https://github.com/user-attachments/assets/29ab35e2-2bce-43d5-a726-f2eb4c4eed37)

**Comment by xiaofan-luan** [comment]
how did that related to milvus? This seems to be a yarn error
