### ISSUE TITLE
Gson Error

### ISSUE THREAD

**Issue by limuyang2** [milvus-io/milvus-sdk-java#1143]
sdk: 2.4.6 - 2.4.7

Caused by: java.lang.IllegalArgumentException: TypeToken type argument must not contain a type variable; captured type variable T declared by public static com.google.gson.JsonElement io.milvus.common.utils.JsonUtils.toJsonTree(java.lang.Object)
See https://github.com/google/gson/blob/main/Troubleshooting.md#typetoken-type-variable
	at com.google.gson.reflect.TypeToken.verifyNoTypeVariable(TypeToken.java:130)
	at com.google.gson.reflect.TypeToken.getTypeTokenTypeArgument(TypeToken.java:103)
	at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:74)
	at io.milvus.common.utils.JsonUtils$1.<init>(JsonUtils.java:70)
	at io.milvus.common.utils.JsonUtils.toJsonTree(JsonUtils.java:70)
	at io.milvus.v2.service.vector.request.ranker.WeightedRanker.getProperties(WeightedRanker.java:43)
	at io.milvus.v2.utils.VectorUtils.ConvertToGrpcHybridSearchRequest(VectorUtils.java:281)
	at io.milvus.v2.service.vector.VectorService.hybridSearch(VectorService.java:188)
	at io.milvus.v2.client.MilvusClientV2.lambda$hybridSearch$28(MilvusClientV2.java:541)
	at io.milvus.v2.client.MilvusClientV2.retry(MilvusClientV2.java:196)

Form Google：

> IllegalArgumentException: 'TypeToken type argument must not contain a type variable'
> Symptom: An exception with the message 'TypeToken type argument must not contain a type variable' is thrown
> 
> Reason: This exception is thrown when you create an anonymous TypeToken subclass which captures a type variable, for example new TypeToken<List<T>>() {} (where T is a type variable). At compile time such code looks safe and you can use the type List<T> without any warnings. However, this code is not actually type-safe because at runtime due to [type erasure](https://dev.java/learn/generics/type-erasure/) only the upper bound of the type variable is available. For the previous example that would be List<Object>. When using such a TypeToken with any Gson methods performing deserialization this would lead to confusing and difficult to debug ClassCastExceptions. For serialization it can in some cases also lead to undesired results.
> 
> Note: Earlier version of Gson unfortunately did not prevent capturing type variables, which caused many users to unwittingly write type-unsafe code.
> 
> Solution:
> 
> Use [TypeToken.getParameterized(...)](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/reflect/TypeToken.html#getParameterized(java.lang.reflect.Type,java.lang.reflect.Type...)), for example TypeToken.getParameterized(List.class, elementType) where elementType is a type you have to provide separately.
> For Kotlin users: Use [reified type parameters](https://kotlinlang.org/docs/inline-functions.html#reified-type-parameters), that means change <T> to <reified T>, if possible. If you have a chain of functions with type parameters you will probably have to make all of them reified.
> If you don't actually use Gson's TypeToken for any Gson method, use a general purpose 'type token' implementation provided by a different library instead, for example Guava's [com.google.common.reflect.TypeToken](https://javadoc.io/doc/com.google.guava/guava/latest/com/google/common/reflect/TypeToken.html).
> For backward compatibility it is possible to restore Gson's old behavior of allowing TypeToken to capture type variables by setting the [system property](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/System.html#setProperty(java.lang.String,java.lang.String)) gson.allowCapturingTypeVariables to "true", however:
> 
> This does not solve any of the type-safety problems mentioned above; in the long term you should prefer one of the other solutions listed above. This system property might be removed in future Gson versions.
> You should only ever set the property to "true", but never to any other value or manually clear it. Otherwise this might counteract any libraries you are using which might have deliberately set the system property because they rely on its behavior.

**Comment by xiaofan-luan** [comment]
> sdk: 2.4.6 - 2.4.7
> 
> Caused by: java.lang.IllegalArgumentException: TypeToken type argument must not contain a type variable; captured type variable T declared by public static com.google.gson.JsonElement io.milvus.common.utils.JsonUtils.toJsonTree(java.lang.Object) See https://github.com/google/gson/blob/main/Troubleshooting.md#typetoken-type-variable at com.google.gson.reflect.TypeToken.verifyNoTypeVariable(TypeToken.java:130) at com.google.gson.reflect.TypeToken.getTypeTokenTypeArgument(TypeToken.java:103) at com.google.gson.reflect.TypeToken.(TypeToken.java:74) at io.milvus.common.utils.JsonUtils$1.(JsonUtils.java:70) at io.milvus.common.utils.JsonUtils.toJsonTree(JsonUtils.java:70) at io.milvus.v2.service.vector.request.ranker.WeightedRanker.getProperties(WeightedRanker.java:43) at io.milvus.v2.utils.VectorUtils.ConvertToGrpcHybridSearchRequest(VectorUtils.java:281) at io.milvus.v2.service.vector.VectorService.hybridSearch(VectorService.java:188) at io.milvus.v2.client.MilvusClientV2.lambda$hybridSearch$28(MilvusClientV2.java:541) at io.milvus.v2.client.MilvusClientV2.retry(MilvusClientV2.java:196)
> 
> Form Google：
> 
> > IllegalArgumentException: 'TypeToken type argument must not contain a type variable'
> > Symptom: An exception with the message 'TypeToken type argument must not contain a type variable' is thrown
> > Reason: This exception is thrown when you create an anonymous TypeToken subclass which captures a type variable, for example new TypeToken<List>() {} (where T is a type variable). At compile time such code looks safe and you can use the type List without any warnings. However, this code is not actually type-safe because at runtime due to [type erasure](https://dev.java/learn/generics/type-erasure/) only the upper bound of the type variable is available. For the previous example that would be List. When using such a TypeToken with any Gson methods performing deserialization this would lead to confusing and difficult to debug ClassCastExceptions. For serialization it can in some cases also lead to undesired results.
> > Note: Earlier version of Gson unfortunately did not prevent capturing type variables, which caused many users to unwittingly write type-unsafe code.
> > Solution:
> > Use [TypeToken.getParameterized(...)](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/reflect/TypeToken.html#getParameterized(java.lang.reflect.Type,java.lang.reflect.Type...)), for example TypeToken.getParameterized(List.class, elementType) where elementType is a type you have to provide separately.
> > For Kotlin users: Use [reified type parameters](https://kotlinlang.org/docs/inline-functions.html#reified-type-parameters), that means change  to , if possible. If you have a chain of functions with type parameters you will probably have to make all of them reified.
> > If you don't actually use Gson's TypeToken for any Gson method, use a general purpose 'type token' implementation provided by a different library instead, for example Guava's [com.google.common.reflect.TypeToken](https://javadoc.io/doc/com.google.guava/guava/latest/com/google/common/reflect/TypeToken.html).
> > For backward compatibility it is possible to restore Gson's old behavior of allowing TypeToken to capture type variables by setting the [system property](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/System.html#setProperty(java.lang.String,java.lang.String)) gson.allowCapturingTypeVariables to "true", however:
> > This does not solve any of the type-safety problems mentioned above; in the long term you should prefer one of the other solutions listed above. This system property might be removed in future Gson versions.
> > You should only ever set the property to "true", but never to any other value or manually clear it. Otherwise this might counteract any libraries you are using which might have deliberately set the system property because they rely on its behavior.


can you share how a sample code that could trigger this error?

**Comment by xiaofan-luan** [comment]
I think the error message need to be cleaned, but this could be generally just an config error

**Comment by yhmo** [comment]
The definition of V2 WeightedRanker:
```
public class WeightedRanker extends BaseRanker {
    private List<Float> weights;
    public WeightedRanker(List<Float> weights) {
        this.weights = weights;
    }
    ......
```

A typical usage of WeightedRanker:
```
        HybridSearchReq hybridSearchReq = HybridSearchReq.builder()
                .collectionName(COLLECTION_NAME)
                .searchRequests(searchRequests)
                .ranker(new WeightedRanker(Arrays.asList(0.2f, 0.5f, 0.6f)))
                .topK(5)
                .consistencyLevel(ConsistencyLevel.BOUNDED)
                .build();
```

The WeightedRanker explicitly requires a List of Float. Something is wrong with your input.

**Comment by limuyang2** [comment]
> > sdk: 2.4.6 - 2.4.7 开发工具包：2.4.6 - 2.4.7
> > Caused by: java.lang.IllegalArgumentException: TypeToken type argument must not contain a type variable; captured type variable T declared by public static com.google.gson.JsonElement io.milvus.common.utils.JsonUtils.toJsonTree(java.lang.Object) See https://github.com/google/gson/blob/main/Troubleshooting.md#typetoken-type-variable at com.google.gson.reflect.TypeToken.verifyNoTypeVariable(TypeToken.java:130) at com.google.gson.reflect.TypeToken.getTypeTokenTypeArgument(TypeToken.java:103) at com.google.gson.reflect.TypeToken.(TypeToken.java:74) at io.milvus.common.utils.JsonUtils$1.(JsonUtils.java:70) at io.milvus.common.utils.JsonUtils.toJsonTree(JsonUtils.java:70) at io.milvus.v2.service.vector.request.ranker.WeightedRanker.getProperties(WeightedRanker.java:43) at io.milvus.v2.utils.VectorUtils.ConvertToGrpcHybridSearchRequest(VectorUtils.java:281) at io.milvus.v2.service.vector.VectorService.hybridSearch(VectorService.java:188) at io.milvus.v2.client.MilvusClientV2.lambda$hybridSearch$28(MilvusClientV2.java:541) at io.milvus.v2.client.MilvusClientV2.retry(MilvusClientV2.java:196)原因：java.lang.IllegalArgumentException：TypeToken 类型参数不得包含类型变量;由公共静态 com.google.gson.JsonElement io.milvus.common.utils.JsonUtils.toJsonTree（java.lang.Object） 声明的捕获类型变量 T 请参阅 com.google.gson.reflect.TypeToken.verifyNoTypeVariable（TypeToken.java：130） https://github.com/google/gson/blob/main/Troubleshooting.md#typetoken-type-variable com.google.gson.reflect.TypeToken.getTypeTokenTypeArgument（TypeToken.java：103） 在 com.google.gson.reflect.TypeToken 中。（TypeToken.java：74） 在 io.milvus.common.utils.JsonUtils$1 中。（JsonUtils.java：70） 在 io.milvus.common.utils.JsonUtils.toJsonTree（JsonUtils.java：70） 在 io.milvus.v2.service.vector.request.ranker.WeightedRanker.getProperties（WeightedRanker.java：43） 在 io.milvus.v2.utils.VectorUtils.ConvertToGrpcHybridSearchRequest（VectorUtils.java：281） 在 io.milvus.v2.service.vector.VectorService.hybridSearch（VectorService.java：188） 在 io.milvus.v2.client.MilvusClientV2.lambda$hybridSearch$28（MilvusClientV2.java：541）io.milvus.v2.client.MilvusClientV2.retry（MilvusClientV2.java：196）
> > Form Google： 形成 Google：
> > > IllegalArgumentException: 'TypeToken type argument must not contain a type variable'IllegalArgumentException： “TypeToken 类型参数不得包含类型变量”
> > > Symptom: An exception with the message 'TypeToken type argument must not contain a type variable' is thrown症状：引发异常，并显示消息“TypeToken type argument must not contain a type variable”
> > > Reason: This exception is thrown when you create an anonymous TypeToken subclass which captures a type variable, for example new TypeToken() {} (where T is a type variable). At compile time such code looks safe and you can use the type List without any warnings. However, this code is not actually type-safe because at runtime due to [type erasure](https://dev.java/learn/generics/type-erasure/) only the upper bound of the type variable is available. For the previous example that would be List. When using such a TypeToken with any Gson methods performing deserialization this would lead to confusing and difficult to debug ClassCastExceptions. For serialization it can in some cases also lead to undesired results.原因：当您创建捕获类型变量的匿名 TypeToken 子类时，会引发此异常，例如 new TypeToken（） {}（其中 T 是类型变量）。在编译时，此类代码看起来很安全，并且你可以使用 List 类型，而不会发出任何警告。但是，此代码实际上并不是类型安全的，因为在运行时，由于[类型擦除](https://dev.java/learn/generics/type-erasure/)，只有类型变量的上限可用。对于前面的示例，该字段为 List。当将这样的 TypeToken 与任何执行反序列化的 Gson 方法一起使用时，这会导致混淆且难以调试 ClassCastExceptions。对于序列化，在某些情况下，它还可能导致意外结果。
> > > Note: Earlier version of Gson unfortunately did not prevent capturing type variables, which caused many users to unwittingly write type-unsafe code.注意：不幸的是，早期版本的 Gson 并没有阻止捕获类型变量，这导致许多用户无意中编写了类型不安全的代码。
> > > Solution: 溶液：
> > > Use [TypeToken.getParameterized(...)](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/reflect/TypeToken.html#getParameterized(java.lang.reflect.Type,java.lang.reflect.Type...)), for example TypeToken.getParameterized(List.class, elementType) where elementType is a type you have to provide separately.使用 [TypeToken.getParameterized（...），](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/reflect/TypeToken.html#getParameterized(java.lang.reflect.Type,java.lang.reflect.Type...))例如 TypeToken.getParameterized（List.class， elementType），其中 elementType 是您必须单独提供的类型。
> > > For Kotlin users: Use [reified type parameters](https://kotlinlang.org/docs/inline-functions.html#reified-type-parameters), that means change  to , if possible. If you have a chain of functions with type parameters you will probably have to make all of them reified.对于 Kotlin 用户：使用[具体化类型参数](https://kotlinlang.org/docs/inline-functions.html#reified-type-parameters)，这意味着如果可能，请更改为 。如果你有一个带有类型参数的函数链，你可能必须使它们全部具体化。
> > > If you don't actually use Gson's TypeToken for any Gson method, use a general purpose 'type token' implementation provided by a different library instead, for example Guava's [com.google.common.reflect.TypeToken](https://javadoc.io/doc/com.google.guava/guava/latest/com/google/common/reflect/TypeToken.html).如果您实际上并未将 Gson 的 TypeToken 用于任何 Gson 方法，请改用其他库提供的通用“类型令牌”实现，例如 Guava 的 [com.google.common.reflect.TypeToken](https://javadoc.io/doc/com.google.guava/guava/latest/com/google/common/reflect/TypeToken.html)。
> > > For backward compatibility it is possible to restore Gson's old behavior of allowing TypeToken to capture type variables by setting the [system property](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/System.html#setProperty(java.lang.String,java.lang.String)) gson.allowCapturingTypeVariables to "true", however:但是，为了向后兼容，可以通过将[系统属性](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/System.html#setProperty(java.lang.String,java.lang.String)) gson.allowCapturingTypeVariables 设置为 “true” 来恢复 Gson 允许 TypeToken 捕获类型变量的旧行为：
> > > This does not solve any of the type-safety problems mentioned above; in the long term you should prefer one of the other solutions listed above. This system property might be removed in future Gson versions.这并不能解决上面提到的任何类型安全问题;从长远来看，您应该更喜欢上面列出的其他解决方案之一。此系统属性可能会在未来的 Gson 版本中删除。
> > > You should only ever set the property to "true", but never to any other value or manually clear it. Otherwise this might counteract any libraries you are using which might have deliberately set the system property because they rely on its behavior.您应该只将属性设置为 “true”，而不应该设置为任何其他值或手动清除它。否则，这可能会抵消您正在使用的任何库，这些库可能故意设置了 system 属性，因为它们依赖于其行为。
> 
> can you share how a sample code that could trigger this error?您能否分享一下如何触发此错误的示例代码？

user V2  hybridSearch()

**Comment by limuyang2** [comment]
> ranker

yes, I'm using float.
However, if you look at the error log, it is a json error inside the SDK caused by hybridSearch (), and GSON also gives a link in the error message, which is clearly a compatibility issue.

Form SDK source code:
```
SON_INSTANCE.toJsonTree(obj, new TypeToken<T>() {}.getType());
```
Now, `TypeToken<T>() {}.getType()` is the wrong use.

Gson asks for Safe usage: `TypeToken.getParameterized`

**Comment by limuyang2** [comment]
> The definition of V2 WeightedRanker:
> 
> ```
> public class WeightedRanker extends BaseRanker {
>     private List<Float> weights;
>     public WeightedRanker(List<Float> weights) {
>         this.weights = weights;
>     }
>     ......
> ```
> 
> A typical usage of WeightedRanker:
> 
> ```
>         HybridSearchReq hybridSearchReq = HybridSearchReq.builder()
>                 .collectionName(COLLECTION_NAME)
>                 .searchRequests(searchRequests)
>                 .ranker(new WeightedRanker(Arrays.asList(0.2f, 0.5f, 0.6f)))
>                 .topK(5)
>                 .consistencyLevel(ConsistencyLevel.BOUNDED)
>                 .build();
> ```
> 
> The WeightedRanker explicitly requires a List of Float. Something is wrong with your input.

yes, I'm using float.
However, if you look at the error log, it is a json error inside the SDK caused by hybridSearch (), and GSON also gives a link in the error message, which is clearly a compatibility issue.

From SDK source code:
```
GSON_INSTANCE.toJsonTree(obj, new TypeToken<T>() {}.getType());
```
Now, `TypeToken<T>() {}.getType()` is the wrong use.

Gson asks for Safe usage: `TypeToken.getParameterized`

**Comment by yhmo** [comment]
> > The definition of V2 WeightedRanker:
> > ```
> > public class WeightedRanker extends BaseRanker {
> >     private List<Float> weights;
> >     public WeightedRanker(List<Float> weights) {
> >         this.weights = weights;
> >     }
> >     ......
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > A typical usage of WeightedRanker:
> > ```
> >         HybridSearchReq hybridSearchReq = HybridSearchReq.builder()
> >                 .collectionName(COLLECTION_NAME)
> >                 .searchRequests(searchRequests)
> >                 .ranker(new WeightedRanker(Arrays.asList(0.2f, 0.5f, 0.6f)))
> >                 .topK(5)
> >                 .consistencyLevel(ConsistencyLevel.BOUNDED)
> >                 .build();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The WeightedRanker explicitly requires a List of Float. Something is wrong with your input.
> 
> yes, I'm using float. However, if you look at the error log, it is a json error inside the SDK caused by hybridSearch (), and GSON also gives a link in the error message, which is clearly a compatibility issue.
> 
> From SDK source code:
> 
> ```
> GSON_INSTANCE.toJsonTree(obj, new TypeToken<T>() {}.getType());
> ```
> 
> Now, `TypeToken<T>() {}.getType()` is the wrong use.
> 
> Gson asks for Safe usage: `TypeToken.getParameterized`

Could you show me the code to reproduce the error? I just want to confirm it.

**Comment by limuyang2** [comment]
> > > The definition of V2 WeightedRanker:
> > > ```
> > > public class WeightedRanker extends BaseRanker {
> > >     private List<Float> weights;
> > >     public WeightedRanker(List<Float> weights) {
> > >         this.weights = weights;
> > >     }
> > >     ......
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > A typical usage of WeightedRanker:
> > > ```
> > >         HybridSearchReq hybridSearchReq = HybridSearchReq.builder()
> > >                 .collectionName(COLLECTION_NAME)
> > >                 .searchRequests(searchRequests)
> > >                 .ranker(new WeightedRanker(Arrays.asList(0.2f, 0.5f, 0.6f)))
> > >                 .topK(5)
> > >                 .consistencyLevel(ConsistencyLevel.BOUNDED)
> > >                 .build();
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The WeightedRanker explicitly requires a List of Float. Something is wrong with your input.
> > 
> > 
> > yes, I'm using float. However, if you look at the error log, it is a json error inside the SDK caused by hybridSearch (), and GSON also gives a link in the error message, which is clearly a compatibility issue.
> > From SDK source code:
> > ```
> > GSON_INSTANCE.toJsonTree(obj, new TypeToken<T>() {}.getType());
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now, `TypeToken<T>() {}.getType()` is the wrong use.
> > Gson asks for Safe usage: `TypeToken.getParameterized`
> 
> In your project, the gson lib version has been overwritten to >= 2.11.0, right? By the way, are you using Kotlin?

Yes

**Comment by yhmo** [comment]
The latest Gson version v2.11.0 added a type-safe checker to TypeToken, which throws this error.
The JsonUtils of Milvus Java SDK declared a TypeToken for Gson.toJsonTree(), which is not the correct way in Gson v2.11.0.
Users will see this error under the condition that Gson version is overridden to v2.11.0 with Java SDK v2.4.6 or v2.4.7.

Now we remove the declaration of TypeToken and directly pass the object to the native method of Gson.
The pr fixed this issue: https://github.com/milvus-io/milvus-sdk-java/pull/1156/files. The next minor version will include this fix.

I verified under both Gson v2.10.0 and Gson v2.11.0, it works well.

**Comment by limuyang2** [comment]
> The latest Gson version v2.11.0 added a type-safe checker to TypeToken, which throws this error. The JsonUtils of Milvus Java SDK declared a TypeToken for Gson.toJsonTree(), which is not the correct way in Gson v2.11.0. Users will see this error under the condition that Gson version is overridden to v2.11.0 with Java SDK v2.4.6 or v2.4.7.
> 
> Now we remove the declaration of TypeToken and directly pass the object to the native method of Gson. The pr fixed this issue: https://github.com/milvus-io/milvus-sdk-java/pull/1156/files. The next minor version will include this fix.
> 
> I verified under both Gson v2.10.0 and Gson v2.11.0, it works well.

Works fine
