### ISSUE TITLE
Missing element_type for Array DataType in FieldSchema for Milvus SDK 2.4.x

### ISSUE THREAD

**Issue by Yiling1f** [milvus-io/milvus-sdk-java#1148]
**Issue Description**
In Milvus SDK 2.4.x, when defining a field with Array data type (e.g., Array<Int32>), the FieldSchema does not provide direct access to the element_type information. This issue limits the ability to retrieve the full type specification (e.g., Array<Int32>) programmatically, as only the base type Array is returned by field.getDataType().name().

**Steps to Reproduce**
1. Define a field in Milvus with Array<Int32> data type in the collection schema.
2. Use MilvusClient.describeCollection to retrieve the collection schema.
3. Attempt to retrieve element_type for the Array field through FieldSchema.getTypeParamsList() or any other available methods.

![image](https://github.com/user-attachments/assets/8f0b6565-9504-4f8a-9d2f-5ae1f2f8fda1)

**Expected Behavior**
The FieldSchema for Array data types should include the element_type (e.g., Int32) as part of typeParamsList or another accessible attribute, allowing users to retrieve the specific array type programmatically.
![image](https://github.com/user-attachments/assets/cea4b541-6f74-4d31-a118-e03bf9bd6289)

**Comment by yhmo** [comment]
```
        List<FieldType> fieldsSchema = Arrays.asList(
                FieldType.newBuilder()
                        .withName("id")
                        .withDataType(DataType.Int64)
                        .withPrimaryKey(true)
                        .withAutoID(false)
                        .build(),
                FieldType.newBuilder()
                        .withName("vector")
                        .withDataType(DataType.FloatVector)
                        .withDimension(128)
                        .build(),
                FieldType.newBuilder()
                        .withName("title")
                        .withDataType(DataType.Array)
                        .withMaxCapacity(100)
                        .withElementType(DataType.VarChar)
                        .withMaxLength(64)
                        .build()
        );

        // Create the collection with 3 fields
        R<RpcStatus> ret = milvusClient.createCollection(CreateCollectionParam.newBuilder()
                .withCollectionName(COLLECTION_NAME)
                .withFieldTypes(fieldsSchema)
                .build());
        if (ret.getStatus() != R.Status.Success.getCode()) {
            throw new RuntimeException("Failed to create collection! Error: " + ret.getMessage());
        }

        R<DescribeCollectionResponse> response = milvusClient.describeCollection(DescribeCollectionParam.newBuilder()
                .withCollectionName(COLLECTION_NAME)
                .build());
        CommonUtils.handleResponseStatus(response);
        DescCollResponseWrapper wrapper = new DescCollResponseWrapper(response.getData());
        FieldType fieldType = wrapper.getFieldByName("title");
        System.out.println(fieldType.getDataType());
        System.out.println(fieldType.getElementType());
```

Output:
```
Array
VarChar
```
