### ISSUE TITLE
[bug] dynamic field is enabled by dynamic values are not inserted (2.5.0)

### ISSUE THREAD

**Issue by javpower** [milvus-io/milvus-sdk-java#1206]
定位问题：SchemaUtils.convertFromGrpcCollectionSchema内enableDynamicField未 set
<img width="1389" alt="image" src="https://github.com/user-attachments/assets/e2f0cc91-aa83-42f8-bede-57534a4b8eb6">

**Comment by yhmo** [comment]
有没有重现的步骤?

我启用了DynamicField
```
client.createCollection(CreateCollectionReq.builder()
                .collectionName(collectionName)
                .dimension(4)
                .enableDynamicField(true)
                .build());
```

然后插入带动态字段数据是成功的
```
Gson gson = new Gson();
JsonObject row = new JsonObject();
row.addProperty("id", 1);
row.add("vector", gson.toJsonTree(new float[]{1.0f,2.0f,3.0f,4.0f}));
row.addProperty("dynamic_val", "this is dynamic value"); // this value is stored in dynamic field
row.addProperty("aaa", 9);
row.addProperty("bbb", true);
InsertResp insertR = client.insert(InsertReq.builder()
        .collectionName(collectionName)
        .data(Collections.singletonList(row))
        .build());
```

**Comment by javpower** [comment]
sdk 2.5.0版本(2.4.x版本没这个问题)，不是指的报错，是额外的数据不会入库
<img width="1152" alt="image" src="https://github.com/user-attachments/assets/25aea2c9-4729-4c9a-8866-b53f13100400">
<img width="897" alt="image" src="https://github.com/user-attachments/assets/5af50cf3-9ca2-4261-9ae9-f226a588e2a7">

**Comment by yhmo** [comment]
确实是2.5.0的bug，感谢指出。我会尽快修正

**Comment by yhmo** [comment]
Fixed by this pr: https://github.com/milvus-io/milvus-sdk-java/pull/1211

**Comment by yhmo** [comment]
v2.5.1 has been released with this fix: https://github.com/milvus-io/milvus-sdk-java/releases/tag/v2.5.1
