### ISSUE TITLE
Milvus 2.5.0 JavaSDK 打包成 jar 后运行失败，无法建立连接

### ISSUE THREAD

**Issue by WanDerer23333** [milvus-io/milvus-sdk-java#1261]
代码本身很简单，在idea里可以直接运行，运行后可以成功打印 database 列表
![image](https://github.com/user-attachments/assets/cdf9a2ad-fb57-4673-9a6c-4a29a95edbec)

但是打包成jar之后就不能成功运行，会报 grpc 超时，怀疑是内部引用有冲突

**Comment by WanDerer23333** [comment]
![image](https://github.com/user-attachments/assets/9093c47b-b56b-49c7-a3bc-a1ebd5b806c6)
bao c报错信息如上

**Comment by WanDerer23333** [comment]
pom文件如下：
![image](https://github.com/user-attachments/assets/30ea4e83-bf7d-4ba8-915a-50595a309595)
![image](https://github.com/user-attachments/assets/6b02ef6d-f75c-40d0-a878-27e4c0eda786)

**Comment by WanDerer23333** [comment]
同样的代码换成 2.3.9:
![image](https://github.com/user-attachments/assets/5ab666ba-bf32-4b51-a121-5bd272d05ea9)
![image](https://github.com/user-attachments/assets/2a9d5c41-b742-45ce-97f6-9622c034e151)
![image](https://github.com/user-attachments/assets/fda568b5-10d9-485a-a11b-c1f2fdb741ff)

**Comment by yhmo** [comment]
这是打包插件和grpc-java包的问题，参考：
https://stackoverflow.com/questions/73286776/grpc-unsupportedaddresstypeexception-but-only-when-packaged-with-shadowjar
https://stackoverflow.com/questions/73554080/unable-to-connect-to-grpc-server-when-build-as-jar

https://community.temporal.io/t/grpc-connection-error-with-temporal-when-i-try-running-jar-while-starting-temporal-worker/10571/3

https://github.com/grpc/grpc-java/issues/9770
https://github.com/grpc/grpc-java/issues/9387

**Comment by yhmo** [comment]
比如有用户用了maven-shade-plugin，加一个transformer就可以解决。

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>3.2.1</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>shade</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <transformers>
            <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
        </transformers>
    </configuration>
</plugin>

**Comment by WanDerer23333** [comment]
Thanks ！！
