### ISSUE TITLE
关于特征值是double的问题

### ISSUE THREAD

**Issue by JsonShare** [milvus-io/milvus-sdk-java#135]
milvus 支持double数据集的插入吗？  api现在只有float

**Comment by JsonShare** [comment]
@youny626

**Comment by sahuang** [comment]
Currently only float values are supported. This is because even if you insert double values, Milvus server will process using floating-point values.

**Comment by sahuang** [comment]
If you wish Milvus to support double precision, feel free to raise a feature request [here](https://github.com/milvus-io/milvus/issues/new?assignees=&labels=&template=feature_request.md&title=).

**Comment by JsonShare** [comment]
tks
