### ISSUE TITLE
While adding new ro-milvus node,  java milvus client can not rebanlace query.

### ISSUE THREAD

**Issue by yu-hailong** [milvus-io/milvus-sdk-java#149]
1. Connect to Milvus by domain name which includes 3 ro nodes
2. Do query, we found the reqeusts is sent to 3 nodes  regularly
3. while removed one nodes from domain name,  reqeusts were rebanlanced to the remained 2 nodes .
--
4. But we tried to add a new node into the domain name, no requests were sent to the new node.
Unless，we inited client and reconnected milvus server, and then requests could be sent to the new node 

So, we suggest, milvus client should know serverlist change and rebanlance request automatically.

**Comment by sahuang** [comment]
Not sure if I understand your question correctly, but Milvus currently supports load balancing using round_robin as default method. There is a simple case that demonstrates this:

```java
@org.junit.jupiter.api.Test
  void loadBalancing() {
    NameResolverProvider testNameResolverProvider = new StaticNameResolverProvider(
        new InetSocketAddress(milvusContainer.getHost(), milvusContainer.getFirstMappedPort()),
        new InetSocketAddress(milvusContainer2.getHost(), milvusContainer2.getFirstMappedPort()));

    NameResolverRegistry.getDefaultRegistry().register(testNameResolverProvider);

    ConnectParam connectParam = connectParamBuilder()
        .withTarget(testNameResolverProvider.getDefaultScheme() + ":///test")
        .build();

    MilvusClient loadBalancingClient = new MilvusGrpcClient(connectParam).withLogging();
    assertEquals(50, IntStream.range(0, 100)
            .filter(i -> loadBalancingClient.hasCollection(randomCollectionName))
            .count());
  }
```

**Comment by sahuang** [comment]
I would also like to add that this is only supported from Milvus v0.11.0.

**Comment by yu-hailong** [comment]
I add a new issue in milvus-io/milvus by  suggestion  from jinhai,  we can dissuss this problem on https://github.com/milvus-io/milvus/issues/4241

**Comment by yu-hailong** [comment]
I mean, in 0.10.3, while keeping client connect to milvus server and adding a new ro node to domain name  meanwhile,
the new node can  not received any request.

**Comment by yu-hailong** [comment]
> I would also like to add that this is only supported from Milvus v0.11.0.

By the way，while deploying on K8S， while we added new node in K8S‘s LB,
client also cannot find the new node.

**Comment by sahuang** [comment]
I understand your question now. Did you give a try at 0.11.0? In 0.10.3 this is not supported.

**Comment by yu-hailong** [comment]
> I understand your question now. Did you give a try at 0.11.0? In 0.10.3 this is not supported.

Thank you， I got it.

**Comment by sahuang** [comment]
If you have any other problem we can discuss it in the issue you opened.
