### ISSUE TITLE
I 've question regarding performance with milvus java-sdk

### ISSUE THREAD

**Issue by soberhjj** [milvus-io/milvus-sdk-java#157]
I ran the official performance test case . The test program is  python scripts. When the script is finished running , I get result as follows .  When I do the same test in  Java way , I get result as follows .  There's a big time difference between picture 1 and picture 2. This is why? Is the Java API slower than python API queries?

pymilvus version: 0.3.0
milvus java sdk version: 0.9.1

The result of running python script:            
nq--- topk---    time(s)                                            
1   --- -     1    ----    0.0053                                            
1   --- -     10   ----   0.0045                                                              
1----         100----    0.0044                                                 
1----         500  ----  0.0047                                                  

 The result of running java test program:
  nq ---   topk---    time(s)
 1 ----        1   ----     0.0079
 1   ----      10  ----    0.0086
 1     ----    100 ----   0.0285
 1   ----      500  ----  0.1157

**Comment by sahuang** [comment]
Can you share your Python and Java test program?

**Comment by sahuang** [comment]
Closed due to inactivity. Feel free to reopen and discuss the issue.
