### ISSUE TITLE
search

### ISSUE THREAD

**Issue by handHuang** [milvus-io/milvus-sdk-java#158]
版本0.11.0
向量插入成功搜索时报异常，异常如下：
io.milvus.client.exception.ServerSideMilvusException: dns:///192.168.38.132:19530: ServerSideMilvusException{errorCode=UNEXPECTED_ERROR, reason=[json.exception.type_error.302] type must be number, but is null}
查询dsl :
 {"bool":{"must":[{"range":{"timestamp":{"gte":1581264000000,"lte":1581350340000}}},{"term":{"cameraId":[2058575720]}},{"vector":{"feature":{"topK":100,"query":[[0.062381104,0.0,0.062175993,0.09636325,0.0,0.0,0.029739523]],"metric_type":"L2","params":{"nprobe":100},"type":"float"}}}]}}
因为日志比较少这边暂时无法确认问题出在哪。

集合信息如下：
{"collectionName":"vehicle","fields":[{"name":"cameraId","type":"INT32","params":"null"},{"name":"feature","type":"VECTOR_FLOAT","params":"{\"dim\":512}"},{"name":"timestamp","type":"INT64","params":"null"}],"paramsInJson":"{\"auto_id\":true,\"segment_row_limit\":1048576}"}
麻烦帮忙看下！

**Comment by handHuang** [comment]
测试代码如下：
  @Override
  public SearchResult search(QueryRequest request) {
    String userId = request.getUserId();
    if (StringUtils.isEmpty(userId)) {
      throw new IllegalArgumentException("userId不能为空");
    }
    List<String> features = request.getFeatures();

    if (null == features || features.isEmpty()) {
      throw new IllegalArgumentException("搜索向量不能为空");
    }

    Long startTime = request.getStartTime();
    Long endTime = request.getEndTime();

    if (null == startTime || null == endTime) {
      throw new IllegalArgumentException("时间范围不能为空");
    }

    List<List<Float>> query = new ArrayList<>();
    for (String feature : features) {
      List<Float> floats = QuantUtil.convertBase64ToArray(feature);
      query.add(floats);
    }

    Integer topK = request.getTopK();
    JSONObject queryDsl = new JSONObject();

    JSONArray must = new JSONArray();
    must.add(
        new JSONObject()
            .fluentPut(
                "range",
                new JSONObject()
                    .fluentPut(
                        TIMESTAMP,
                        new JSONObject().fluentPut("gte", startTime).fluentPut("lte", endTime))));
    List<Integer> cameraIds = request.getCameraIds();
    if (null != cameraIds && !cameraIds.isEmpty()) {
      must.add(
          new JSONObject().fluentPut("term", new JSONObject().fluentPut(CAMERA_ID, cameraIds)));
    }
    must.add(
        new JSONObject()
            .fluentPut(
                "vector",
                new JSONObject()
                    .fluentPut(
                        FEATURE,
                        new JSONObject()
                            .fluentPut("topK", topK)
                            .fluentPut(
                                "params", new JSONObject().fluentPut("nprobe", config.getNprobe()))
                            .fluentPut("metric_type", "L2")
                            .fluentPut("type", "float")
                            .fluentPut("query", query))));
    queryDsl.fluentPut("bool", new JSONObject().fluentPut("must", must));
    // 搜索参数
    SearchParam searchParam = SearchParam.create(collectionName).setDsl(queryDsl.toString());
    // 获取分区
    List<String> parts = QuantUtil.buildParts(partsCache, userId, startTime, endTime);
    if (parts != null && !parts.isEmpty()) {
      // 设置分区,不设置则默认搜索所有分区
      searchParam.setPartitionTags(parts);
    }

    return client.search(searchParam);
  }

**Comment by sahuang** [comment]
`"timestamp":{"gte":1581264000000,"lte":1581350340000}` 
Use `GTE` and `LTE` instead.

`"topK":100`
Use `topk` instead.

I am not sure if this is the real cause, let me know if this works.

**Comment by handHuang** [comment]
谢谢，使用topk 后问题解决了
