### ISSUE TITLE
sdk-java 0.9.1 Exception thread  java.lang.Double(Float) cannot be cast to org.json.JSONArray

### ISSUE THREAD

**Issue by Slash-Wong** [milvus-io/milvus-sdk-java#160]
private VectorRecord toFloatVectorRecord(JSONArray data) {
    return VectorRecord.newBuilder()
        .addAllRecords(
            StreamSupport.stream(data.spliterator(), false)
                .map(element -> (JSONArray) element)
                .map(
                    array -> {
                      int dimension = array.length();
                      List<Float> vector = new ArrayList<>(dimension);
                      for (int i = 0; i < dimension; i++) {
                        vector.add(array.getFloat(i));
                      }
                      return VectorRowRecord.newBuilder().addAllFloatData(vector).build();
                    })
                .collect(Collectors.toList()))
        .build();
  }

通过调试在类 SearchParam 中的toFloatVectorRecord方法会把double或者float强制转换为 JSONArray，则包转换异常

**Comment by sahuang** [comment]
`toFloatVectorRecord` is used to convert a float array in your DSL query into `VectorRecord`. If you put a single float or double number in the query, it will not succeed. 

A simple example here:

https://github.com/milvus-io/milvus-sdk-java/blob/0.9.1/examples/src/main/java/MilvusBasicExample.java#L215-L231

**Comment by Slash-Wong** [comment]
官网的使用说明更新不及时啊。 另外java sdk 0.9.2版本啥时候发

**Comment by sahuang** [comment]
官网之后会在dsl方面做一个更新.

0.9.2将会与milvus 0.11.1一起发布,估计还需要一阵子.

**Comment by sahuang** [comment]
Update: https://milvus.io/cn/docs/v0.11.0/search_entity.md#Java
这边应该是有相关说明的.

**Comment by Slash-Wong** [comment]
0.9.2 的sdk可以使用0.11.0的server么？

**Comment by sahuang** [comment]
可以.
