### ISSUE TITLE
io.milvus.client.exception.UnsupportedDataType: null: Unsupported data type: STRING

### ISSUE THREAD

**Issue by Slash-Wong** [milvus-io/milvus-sdk-java#162]
![异常信息](https://user-images.githubusercontent.com/38338543/103847566-85560880-50db-11eb-9631-91d40265e7d7.PNG)

创建集合时候报 STRING类型不支持？

**Comment by sahuang** [comment]
Please refer to https://github.com/milvus-io/milvus/discussions/4546 for more info.
