### ISSUE TITLE
1.1.0 diff from 1.0.0

### ISSUE THREAD

**Issue by OysterQAQ** [milvus-io/milvus-sdk-java#180]
The interface getEntityByID(String collectionName, List<Long> ids)  in version 1.0.0 seems to be deleted in version 1.1.0.Is this normal? What is the default partitionTag?

**Comment by yhmo** [comment]
@OysterQAQ 
Sorry for late reply. You can create issue on milvus main project so we can see it quickly.

In 1.1.0, we add a parameter "partitionTag" for getEntityByID() and deleteEntityByID(). If you don't want to specify a partition tag, you can set the parameter as empty string.
Just like the the example code, /milvus-sdk-java/examples/src/main/java/MilvusClientExample.java line no.193
```
GetEntityByIDResponse getEntityByIDResponse =
        client.getEntityByID(collectionName, "", vectorIds.subList(0, searchBatchSize));
```
