### ISSUE TITLE
Need Old document for Milvus 0.11.x

### ISSUE THREAD

**Issue by wineternity** [milvus-io/milvus-sdk-java#181]
Hello, we are still using 0.11.x version, and waiting the new release 2.x。
But before the 2.x version released, we need the java document for Milvus 0.11.x。
Could you provided one for this Java SDK.
        <dependency>
            <groupId>io.milvus</groupId>
            <artifactId>milvus-sdk-java</artifactId>
            <version>0.9.0</version>
        </dependency>
Especially need some introduction in DSL for filtering.
Thanks

**Comment by yhmo** [comment]
The java sdk 9.0 is for milvus 0.11.0(experimental), the sdk source code is here:
https://github.com/milvus-io/milvus-sdk-java/tree/v0.9.0

To pull the java sdk 9.0 documentation:
1. git clone https://github.com/milvus-io/milvus-io.github.io
2. git checkout 2aab138025c09a21f0a8076802d2e0288aad8943
After step 2, you can open the home page under /milvus-io.github.io/milvus-sdk-java/javadoc/index.html

**Comment by wineternity** [comment]
> The java sdk 9.0 is for milvus 0.11.0(experimental), the sdk source code is here:
> https://github.com/milvus-io/milvus-sdk-java/tree/v0.9.0
> 
> To pull the java sdk 9.0 documentation:
> 
> 1. git clone https://github.com/milvus-io/milvus-io.github.io
> 2. git checkout 2aab138025c09a21f0a8076802d2e0288aad8943
>    After step 2, you can open the home page under /milvus-io.github.io/milvus-sdk-java/javadoc/index.html
> 
> The DSL design doc is here:
> https://docs.google.com/document/d/1U83LY36TyaG3WD67Q9HWg9saD3qQcz9BfMcEScgwQPM/edit#heading=h.r2eju3sf9da3

thanks so much
