### ISSUE TITLE
使用Java语言怎么将图片转换成特征向量

### ISSUE THREAD

**Issue by liunancun** [milvus-io/milvus-sdk-java#182]
使用Java语言怎么将图片转换成特征向量，官方有没有推荐的方案？

尝试过用Deeplearning4j，但生成的向量跟使用Python生成的不一样

**Comment by yhmo** [comment]
可以在https://github.com/milvus-io/milvus/discussions 上提问，不过我想应该没什么特别的推荐，基本上也是在网上查查找找，看哪个口碑好就用哪个
