### ISSUE TITLE
java sdk for milvus 2.0

### ISSUE THREAD

**Issue by suvashishtha** [milvus-io/milvus-sdk-java#183]
what is the timeline for releasing java sdk for milvus 2.0?

**Comment by yhmo** [comment]
Please refer this roadmap: https://wiki.lfaidata.foundation/display/MIL/Milvus+2.0+Roadmap+and+Time+schedule
Currently Java sdk for 2.0 is still pending, waiting for a developer.

**Comment by haojunyu** [comment]
from https://wiki.lfaidata.foundation/display/MIL/Milvus+2.0+Roadmap+and+Time+schedule, yesterday is the day which to release 2.0-GA and JAVA-SDK。what is the progress of the project？

**Comment by xiaofan-luan** [comment]
> from https://wiki.lfaidata.foundation/display/MIL/Milvus+2.0+Roadmap+and+Time+schedule, yesterday is the day which to release 2.0-GA and JAVA-SDK。what is the progress of the project？

Hi haojun, the main body of SDK is working, but there remains many test tasks so it's not released yet~ we are trying to deliver both GA version and java SDK by the end of next week~

**Comment by yhmo** [comment]
The java sdk for v2.0 is basically ready. You can try the example: https://github.com/milvus-io/milvus-sdk-java/blob/master/examples/main/io/milvus/GeneralExample.java (Note: start a Milvus standalone service before running this example)
Currently the sdk has not been uploaded to Maven repository, you can try it by compile source code and local install.

**Comment by lwsbox** [comment]
what's the plan to upload to Maven Repository?

**Comment by yhmo** [comment]
> what's the plan to upload to Maven Repository?

Depends on Milvus GA release.

**Comment by yhmo** [comment]
Java sdk v2.0.0 has been published on Dec 31, 2021, compatible with Milvus v2.0 RC8 and Pre-GA
Java sdk v2.0.1 has been published today(Jan 18, 2022), compatible with Milvus v2.0 Pre-GA
