### ISSUE TITLE
Is the current version compatible with the 2.0 version of the server?

### ISSUE THREAD

**Issue by limingnihao** [milvus-io/milvus-sdk-java#188]

**Comment by yhmo** [comment]
Current version only support v1.x, cannot compatible with v2.0.

According to his roadmap: https://wiki.lfaidata.foundation/display/MIL/Milvus+2.0+Roadmap+and+Time+schedule
Currently Java sdk for 2.0 is still pending, waiting for a developer.

**Comment by bubblelin** [comment]
Why not speed up

**Comment by xiaofan-luan** [comment]
see also #183
