### ISSUE TITLE
Add Some Basic Test for JAVA SDK

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus-sdk-java#209]
We need some basic test framework to enable unit test of Milvus project . 

The test framework is based on dockercompose, we rely on shell to start a test container and do all kinds of test on the docker.

After the docker, a cleanup will be triggered for resource cleanup.

TODO: need some documents about test requirement and how to run tests

**Comment by yhmo** [comment]
Now this project can use docker to start a Milvus service and run test cases in the io/milvus/client/MilvusClientDockerTest.java.
The test process also automatically runs the docker test cases when a commit is submitted.
Close this issue.
