### ISSUE TITLE
Add precision control for search function by adding round_decimal parameter for Java SDK

### ISSUE THREAD

**Issue by elfisworking** [milvus-io/milvus-sdk-java#213]
python sdk has supported precision control control when search. That feature should be added to java sdk.

**Comment by yhmo** [comment]
Great. It is a valuable feature.

**Comment by yhmo** [comment]
@elfisworking 
The java sdk for v2.0 is basically ready. You can create a pull request once you have a solution to add precision control.

**Comment by yhmo** [comment]
Done
