### ISSUE TITLE
Propose to upgrade log4j-core to 2.17.1

### ISSUE THREAD

**Issue by matrixji** [milvus-io/milvus-sdk-java#250]
#239 introducing the log4j core 2.15.0 to resolve the critical security issue.
And officially, the log4j team released 2.16.0 and 2.17.x to resolve some security issues several days after that event.

**Comment by yhmo** [comment]
Will upgrade it in next minor version.

**Comment by xiaofan-luan** [comment]
Agree, log4j upgrade should be fixed before 2.0GA

**Comment by yhmo** [comment]
Done
