### ISSUE TITLE
The submitted source is missing the io.milvus.grpc package

### ISSUE THREAD

**Issue by doudou0601** [milvus-io/milvus-sdk-java#254]
The submitted source is missing the io.milvus.grpc package

**Comment by yhmo** [comment]
I think you need to reload the project.
My steps:
1. Download the source code zip file, unzip it
2. Use IDE to open the project folder. I use the IntelliJ community edition.
3. Use maven compile the project, the command is `mvn compile -f  pom.xml`. After compile, you will see the io.milvus.grpc classes generated under the `/target/generated-sources/protobuf/java/io/milvus/grpc`
4. Use IDE to reload the project. In IntelliJ, right-click the root node of Project panel, and choose **maven** => **Reload project**

**Comment by yhmo** [comment]
Answered and inactive, close it.
