### ISSUE TITLE
[Enhancement]: Implement multi-cluster failover in milvus-sdk-java

### ISSUE THREAD

**Issue by huazaizai0322** [milvus-io/milvus-sdk-java#264]
I hava two issues as:
1. When cluster is unhealthy, I can not search util cluster recovery.
2. When a querynode is restarted, I will search timeout util this querynode completely load.

These two issues reduce the stability of the cluster, so I will implement multi-cluster failover in milvus-sdk-java.

I will add some features in milvus-sdk-java as:
1. Multi-culster register.
2. Server monitor.
3. Server listener.

I will do this feature, I will open source to milvus-io/milvus-sdk-java.

**Comment by xiaofan-luan** [comment]
@huazaizai0322 any detailed implementation details? we need more documents or descriptions on the issue so we can also implement similar strategy on other SDKs

**Comment by huazaizai0322** [comment]
> @huazaizai0322 any detailed implementation details? we need more documents or descriptions on the issue so we can also implement similar strategy on other SDKs

1. Multi-cluster register, each cluster create a MilvusClient.
2. Add server monitor, it can check clutser health state by listener.
3. Add two server listeners. A listener send the heartbeat that call /healthz restful api, another listener send the hearbeat that search similar from health_check collection of user created.

**Comment by codersky** [comment]
@huazaizai0322 if needed, we can provide more detailed doc

**Comment by yhmo** [comment]
#272
