### ISSUE TITLE
where is io.milvus.grpc

### ISSUE THREAD

**Issue by MultiChen** [milvus-io/milvus-sdk-java#273]
cannot find package:grpc from io.milvus

**Comment by yhmo** [comment]
The package is generated by proto files under this folder:  src/main/milvus-proto/proto/
The folder src/main/milvus-proto is a git submodule, to sync the submodule, go to the milvus-sdk-java root part, and run this command in terminal:
`git submodule update --init`

After this command, you will see three files under src/main/milvus-proto/proto/
milvus.proto
common.proto
schema.proto

Then use a Java IDE to open the project, run maven compile to generate io.milvus.grpc package.

I use IntelliJ (community edition) to compile the project.

**Comment by MultiChen** [comment]
get it,Thank you very much!

**Comment by never7c** [comment]
#479 请帮忙看一下
