### ISSUE TITLE
Support 4 kinds of Consistency level

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus-sdk-java#277]
Now Java SDK only supports 2 kinds of consistency levels: Strong and Eventually.

But Python SDK already supports 4 kinds of consistency levels: Strong, Bounded, Session, and Eventually.

Java SDK also needs to support the other 2 kinds of consistency levels. It will be more convenient and flexible for users.

**Comment by simonaries** [comment]
How to set a consistency level when creating a table in Java？

**Comment by yhmo** [comment]
Bounded is supported, but we don't intend to support Session in Java sdk
