### ISSUE TITLE
In GeneralExample Demo Have a Problem

### ISSUE THREAD

**Issue by Anandonzy** [milvus-io/milvus-sdk-java#292]
https://github.com/milvus-io/milvus-sdk-java/blob/master/examples/main/io/milvus/GeneralExample.java#L527
This`search` function maybe can not search what not in `VECTOR_FIELD`
` searchExpr = AGE_FIELD + " <= 30";
        example.searchProfile(searchExpr);`
 When I use this,It have a Exception "Exception in thread "main" io.milvus.exception.ParamException: Illegal field name: userAge"
 I think this code need to add some instructions.

**Comment by xiaofan-luan** [comment]
could you share you test code so we could help on investigating it?

**Comment by Anandonzy** [comment]
Your GeneralExample code.
`        String searchExpr = AGE_FIELD + " > 20";
        example.searchFace(searchExpr);`

**Comment by yhmo** [comment]
@ThorZilliz Could you help investigate this issue?

**Comment by ThorZilliz** [comment]
ok !

**Comment by ThorZilliz** [comment]
@Anandonzy hi bro,I try many times,can not get the exception. could you show me your test case.
![image](https://user-images.githubusercontent.com/104345188/172380696-c973fa96-054c-40d7-a6a2-c4af17eb33ae.png)
