### ISSUE TITLE
Invoke milvusClient.getIndexBuildProgress return "no index is created" when created Index first

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus-sdk-java#299]
![xi5UbjTQiI](https://user-images.githubusercontent.com/103410837/171190120-005befc5-60d5-408a-b391-634ae5525bde.jpg)
step:
1.create collection
2.create index 
3.getIndexBuildProgress

**Comment by yhmo** [comment]
Test with latest dev build, not reproduciable.

**Comment by yongpengli-z** [comment]
![image](https://user-images.githubusercontent.com/103410837/177287631-6bd35a2a-115f-4cf5-9f5d-4d4c48e9ffb8.png)
[Issue299.java.zip](https://github.com/milvus-io/milvus-sdk-java/files/9044790/Issue299.java.zip)

**Comment by yhmo** [comment]
Fixed by #326

**Comment by yongpengli-z** [comment]
verify pass
