### ISSUE TITLE
为啥源码没有grpc目录讷

### ISSUE THREAD

**Issue by qinjie1314520** [milvus-io/milvus-sdk-java#300]
我下在源码下来，发现
![图片](https://user-images.githubusercontent.com/48704312/171542573-3231349c-867e-459d-8e51-899c5592c6cf.png)
少了个grpc目录吗

**Comment by yhmo** [comment]
参考这个：https://github.com/milvus-io/milvus-sdk-java/issues/273

**Comment by qinjie1314520** [comment]
谢谢大佬
