### ISSUE TITLE
Invoke milvusClient.getIndexState return "index not exist" when created Index first 

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus-sdk-java#302]
correlation issue： https://github.com/milvus-io/milvus-sdk-java/issues/299

**Comment by yhmo** [comment]
Test with the latest dev build, not reproduciable.

**Comment by yongpengli-z** [comment]
![image](https://user-images.githubusercontent.com/103410837/177279307-f2dbcd43-338a-4381-b419-ba5db583553e.png)
[Issue302.java.zip](https://github.com/milvus-io/milvus-sdk-java/files/9044460/Issue302.java.zip)

**Comment by yhmo** [comment]
Fixed by #326

**Comment by yongpengli-z** [comment]
verify pass
