### ISSUE TITLE
The data type of primary key need support String type.

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus-sdk-java#304]
![image](https://user-images.githubusercontent.com/103410837/172291744-0291e463-9c2a-4a4c-a7d6-8aaa10940620.png)

**Comment by yhmo** [comment]
The DataType.String is not supported, yet. The server will return this error if a field is DataType.String.
The #316 will disable DataType.String in java sdk.

**Comment by yongpengli-z** [comment]
Verify pass
