### ISSUE TITLE
[Search]:Search float vector with MetricType.JACCARD return success

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus-sdk-java#313]
float  vector search not support MetricType.JACCARD,should throw exceptions

**Comment by yhmo** [comment]
Pymilvus also has such problem.

**Comment by yhmo** [comment]
#330 partially fixes this issue. If user inputs float vectors to search, he must input correct metric type(L2/IP), otherwise, the SearchParam.build() will throw an exception. Same with binary vectors.

**Comment by yongpengli-z** [comment]
verify passed
