### ISSUE TITLE
milvus DataType

### ISSUE THREAD

**Issue by x-ultimate** [milvus-io/milvus-sdk-java#318]
![image](https://user-images.githubusercontent.com/18657682/177075410-e2d90233-6dfe-4600-bc1f-a9437bcbee5d.png)

use Int8 ,insert scene value is 25, but insert after is not my value.

![image](https://user-images.githubusercontent.com/18657682/177075853-d69eb5ae-b7a1-466d-a37b-7699457df181.png)

**Comment by yhmo** [comment]
This is a bug of attu.
By using query() method, both pymilvus and java SDK work well to query the int8 values.
