### ISSUE TITLE
[CreateIndex]-When create index with SyncMode=True, retrun: 'CreateIndexRequest in sync mode failed: error code: Success'

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus-sdk-java#321]
milvusClient.createIndex(
            CreateIndexParam.newBuilder()
                .withCollectionName(collection)
                .withFieldName(CommonData.defaultVectorField)
                .withIndexName(CommonData.defaultIndex)
                .withMetricType(MetricType.L2)
                .withIndexType(IndexType.IVF_FLAT)
                .withExtraParam(CommonData.defaultExtraParam)
                .withSyncMode(Boolean.TRUE)
                .withSyncWaitingInterval(800L)
                .withSyncWaitingTimeout(30L)
                .build());

**Comment by yhmo** [comment]
Not reproducible in latest dev build.

**Comment by yongpengli-z** [comment]
Confirm no problem by java-sdk-2.1.0-beta2
