### ISSUE TITLE
[GetQuerySegmentInfo]-GetQuerySegmentInfoRequest failed: getSegmentInfo: queryNode 7 is offline

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus-sdk-java#322]
milvusClient.loadCollection(
        LoadCollectionParam.newBuilder().withCollectionName(CommonData.defaultCollection).build());
 R<GetQuerySegmentInfoResponse> responseR =
        milvusClient.getQuerySegmentInfo(
            GetQuerySegmentInfoParam.newBuilder()
                .withCollectionName(CommonData.defaultCollection)
                .build());

**Comment by yhmo** [comment]
Server side problem, the getQuerySegmentInfo() api might be deprecated.
