### ISSUE TITLE
对于scalar field的index创建，这个indexType应该非必选吧？

### ISSUE THREAD

**Issue by hellwhj** [milvus-io/milvus-sdk-java#332]
https://github.com/milvus-io/milvus-sdk-java/blob/fbfba7975746dff19649b03ef5d64461cb562050/src/main/java/io/milvus/param/index/CreateIndexParam.java#L216

**Comment by yhmo** [comment]
Varchar is a new type that allow index, only support one type index currently, the index type is "Trie". I need to add this new type to the IndexType enum. Will do this in beta3.

**Comment by hellwhj** [comment]
> 

我要创建的不是string类型字段的索引，而是int32或者int64的，也是用“stridx”吗？

**Comment by yhmo** [comment]
int8/int16/int32/int64/float/double 这些字段目前不支持建索引。
如果将来支持建索引的话，会有对应的IndexType。
如果现在对int8/int16/int32/int64/float/double 这些字段调用CreateIndex()，是没有效果的。

**Comment by yhmo** [comment]
2.2.8增加了IndexType.SORT，用于设置int8/int16/int32/int64/float/double的索引
