### ISSUE TITLE
[CreateIndex]--Create index failed,when the index type use IVF_HNSW,IVF_PQ,IVF_SQ8,IVF_HNSW and so on 

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus-sdk-java#335]
Index type 'IVF_FLAT ' could be created success.

 public static void main(String[] args) {
        //connect
        MilvusServiceClient milvusClient =
                new MilvusServiceClient(
                        ConnectParam.newBuilder()
                                .withHost("10.98.0.8")
                                .withPort(19530)
                                .build());
        // create collection
        String collectionName = "Collection_issue311";
        FieldType fieldType1 =
                FieldType.newBuilder()
                        .withName("book_id")
                        .withDataType(DataType.Int64)
                        .withPrimaryKey(true)
                        .withAutoID(false)
                        .build();
        FieldType fieldType2 =
                FieldType.newBuilder().withName("word_count").withDataType(DataType.Int64).build();
        FieldType fieldType3 =
                FieldType.newBuilder()
                        .withName("VectorFieldAutoTest")
                        .withDataType(DataType.FloatVector)
                        .withDimension(128)
                        .build();
        CreateCollectionParam createCollectionReq =
                CreateCollectionParam.newBuilder()
                        .withCollectionName(collectionName)
                        .withDescription("Test" + collectionName + "search")
                        .withShardsNum(2)
                        .addFieldType(fieldType1)
                        .addFieldType(fieldType2)
                        .addFieldType(fieldType3)
                        .build();
        R<RpcStatus> collection = milvusClient.createCollection(createCollectionReq);
        // create index
        R<RpcStatus> index = milvusClient.createIndex(
                CreateIndexParam.newBuilder()
                        .withCollectionName(collectionName)
                        .withFieldName("VectorFieldAutoTest")
                        .withIndexName("IndexAutoTest")
                        .withMetricType(MetricType.IP)
                        .withIndexType(IndexType.IVF_HNSW)
                        .withExtraParam("{\"nlist\":1024}")
                        .withSyncMode(Boolean.FALSE)
                        .build());
        System.out.println("create index first:"+ index.getData());

**Comment by yhmo** [comment]
Fixed by #336

**Comment by yongpengli-z** [comment]
Verify pass
