### ISSUE TITLE
[CreateIndex]--Binary vector collection create index failed: invalid index params: map[dim:128 index_type:BIN_IVF_FLAT metric_type:SUBSTRUCTURE nlist:1024]

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus-sdk-java#338]
![image](https://user-images.githubusercontent.com/103410837/179134541-f4b3cac8-966b-41f0-926e-790d8b863356.png)

**Comment by yhmo** [comment]
SUPERSTRUCTURE and SUBSTRUCTURE only support BIN_FLAT
