### ISSUE TITLE
query empty Entity but response R{exception=Exception: emptly collection, status=26, data=null}

### ISSUE THREAD

**Issue by zhansg** [milvus-io/milvus-sdk-java#364]
when query a not existent data, the response is "queryResultsR: R{exception=Exception: emptly collection, status=26, data=null}", it's too scary, because I've really encountered this kind of situation. suggeste to correct the reply information, such as "empty entity".
my milvus-sdk-java version: 2.0.4, If fixed, ignore it.

**Comment by yhmo** [comment]
Already fixed. No exception thrown if the collection is empty. Close this issue.
