### ISSUE TITLE
标量字段query查询时, 查询结果为空时报会打印error级别日志

### ISSUE THREAD

**Issue by zhansg** [milvus-io/milvus-sdk-java#368]
标量字段query查询时, 查询结果为空时报会打印error日志
ERROR 16824 ---  i.m.client.AbstractMilvusGrpcClient      : QueryRequest returns nothing: empty collection or improper expression
请问, 能不能查结果为空的情况给个单独日志, 与empty collection or improper expression分开, 或者调整日志级别不要给error。线上打error日志会被记录。
![image](https://user-images.githubusercontent.com/35246719/184311997-d380146e-b3fd-4b0c-8966-9d8f8283cbcb.png)

**Comment by yhmo** [comment]
@zhansg 
我觉的这里可以改成logWarn()。不知改成warn你那边可以接受么？

**Comment by zhansg** [comment]
> @zhansg 我觉的这里可以改成logWarn()。不知改成warn你那边可以接受么？

当然可以。这个问题我不得不配置logback把milvus日志off了  #笑哭

**Comment by yhmo** [comment]
> > @zhansg 我觉的这里可以改成logWarn()。不知改成warn你那边可以接受么？
> 
> 当然可以。这个问题我不得不配置logback把milvus日志off了 #笑哭

已改：
https://github.com/milvus-io/milvus-sdk-java/pull/370/files
