### ISSUE TITLE
milvus 重启后一段时间无法查询数据

### ISSUE THREAD

**Issue by wangnimaa** [milvus-io/milvus-sdk-java#369]
我们的milvus 有1百万多万的数据量，重启docker节点后，java sdj查询milvus会有大概30分钟无法查询到数据，attu 页面工具也无法查询。

**Comment by yhmo** [comment]
Attu使用的是NodeJS的sdk，两种sdk都无法查询，这是milvus server那边卡在某个地方了。先看你的milvus是哪个版本，如果是2.0.2的话，这种问题还不少。

**Comment by wangnimaa** [comment]
> Attu使用的是NodeJS的sdk，两种sdk都无法查询，这是milvus server那边卡在某个地方了。先看你的milvus是哪个版本，如果是2.0.2的话，这种问题还不少。

我们是用的2.0.2版本，目前有解决方案吗？

**Comment by yhmo** [comment]
> > Attu使用的是NodeJS的sdk，两种sdk都无法查询，这是milvus server那边卡在某个地方了。先看你的milvus是哪个版本，如果是2.0.2的话，这种问题还不少。
> 
> 我们是用的2.0.2版本，目前有解决方案吗？

建议升级到最新的2.1.1吧。2.1.2也快要出来了，就这两天出来。目前2.1的小版本一直在努力修复各种稳定性问题，包括大量在2.0.2上出现的问题。

**Comment by wangnimaa** [comment]
> > > Attu使用的是NodeJS的sdk，两种sdk都无法查询，这是milvus server那边卡在某个地方了。先看你的milvus是哪个版本，如果是2.0.2的话，这种问题还不少。
> > 
> > 
> > 我们是用的2.0.2版本，目前有解决方案吗？
> 
> 建议升级到最新的2.1.1吧。2.1.2也快要出来了，就这两天出来。目前2.1的小版本一直在努力修复各种稳定性问题，包括很多在2.0.2上出现的严重问题。

好的，感谢！
