### ISSUE TITLE
loadCollection java sdk

### ISSUE THREAD

**Issue by x-ultimate** [milvus-io/milvus-sdk-java#377]
我们使用的milvus 版本为2.1.1,queryNode 中 cacheSize 为20G，Java sdk。

1.如果cacheSize 内存用完，是否会启用内存淘汰策略，淘汰后再次查询是否需要先调用loadCollection方法。

2.sdk如何查询releaseCollection 和loadCollection的状态.

**Comment by wangnimaa** [comment]
3.loadCollection方法是否具有幂等性，多次调用是否会反复加载到内存

**Comment by yhmo** [comment]
1. 不会有内存淘汰策略
2. getLoadState()
3. loadCollection方法是幂等的

**Comment by xiaofan-luan** [comment]
如果有nvme磁盘，可以尝试用2.2的diskANN或者2.3的mmap功能
