### ISSUE TITLE
Milvus java sdk is too slow for the first call

### ISSUE THREAD

**Issue by cxxzc** [milvus-io/milvus-sdk-java#378]
Hello,

Currently I am trying to use milvus java sdk to search, but I found that the first time cost is nearly 1s, but after changing the search vector for the second time, the  time-consuming is significantly reduced. Is there any way to preheat?

`1：searchTopK end.cost = 00:00:00.778；
2：searchTopK end.cost = 00:00:00.124；
3：searchTopK end.cost = 00:00:00.100;
4：searchTopK end.cost = 00:00:00.071`

**Comment by yhmo** [comment]
The first call is slow because the java sdk relies on fastjson, the fastjson requires a hundred milliseconds to warm up.
