### ISSUE TITLE
ConsistencyLevel in java sdk

### ISSUE THREAD

**Issue by cxxzc** [milvus-io/milvus-sdk-java#402]
hello，
will the milvus java sdk support specifying consistency when creating collections, like the milvus python sdk does
As the picture shows：
![image](https://user-images.githubusercontent.com/28751037/199640639-f289a712-bad3-4c3c-8fa1-e4dbfb65a6ce.png)

**Comment by yhmo** [comment]
Already supported: https://milvus.io/api-reference/java/v2.2.x/Collection/createCollection().md

`CreateCollectionParam.withConsistencyLevel(ConsistencyLevelEnum consistencyLevel)`
