### ISSUE TITLE
Add validation to InsertParam while building to check if the vector is List<List<Flost>> or List<ByteBuffer>.

### ISSUE THREAD

**Issue by jeet129** [milvus-io/milvus-sdk-java#413]
Currently there is a validation in SearchParam to check if vector is List<List<Flost>> or List<ByteBuffer>. But the similar validation doesn't exist for InsertParam, and it is validated only during the actual insert call. 
Ideally it should be done during the IndexParam build step itself.

**Comment by yhmo** [comment]
This has been fixed in a previous version. The related code is here: https://github.com/milvus-io/milvus-sdk-java/blob/2a03a71583a51683770c157833291fe75402f407/src/main/java/io/milvus/param/ParamUtils.java#L59
