### ISSUE TITLE
Add method in SearchResultsWrapper to check whether the result is empty or not

### ISSUE THREAD

**Issue by jeet129** [milvus-io/milvus-sdk-java#414]
Currently there is no way to check if the SearchResult is empty or not and only while iterating using the below code snippet user has to catch the exception "Result ids is illegal" to conclude that result may be empty. 

> for (int i = 0; i < inputSize; ++i) {
>                 List<SearchResultsWrapper.IDScore> scores = wrapper.getIDScore(i);
>                 searchResult.add(scores.stream().map(score -> {
>                     if (idType == FieldType.LONG) {
>                         return new SearchResult<>(score.getLongID(), score.getScore());
>                     } else {
>                         return new SearchResult<>(score.getStrID(), score.getScore());
>                     }
>                 }).collect(Collectors.toList()));
>             }

Please enhance the Wrapper to have a way to check for emptiness

**Comment by yelusion2** [comment]
https://github.com/milvus-io/milvus/issues/21007
