### ISSUE TITLE
Add build() to GetLoadingProgressParam.Builder

### ISSUE THREAD

**Issue by andrwtokar** [milvus-io/milvus-sdk-java#426]
[GetLoadingProgressParam](https://github.com/milvus-io/milvus-sdk-java/blob/v2.2.2/src/main/java/io/milvus/param/collection/GetLoadingProgressParam.java) has a Builder but doesn't have a build function.

**Comment by yelusion2** [comment]
https://github.com/milvus-io/milvus-sdk-java/commit/2a167a279680a1914588469d719e46aff30f43ef#diff-7f5610b6ed11672dffff2cca997ccc65a1a341ef0e2d644b881152ecf8bb1651
