### ISSUE TITLE
Cosine similarity - please help

### ISSUE THREAD

**Issue by kubecutle** [milvus-io/milvus-sdk-java#464]
I saw the previous thread saying that you can achieve cosine similarity by using MetricType.IP. And so I tried it. I use MetricType.IP on the index as well as on the search. But this gives me scores around 400 and more. Can you please help me understand how I can actually get distances between 0 and 1?

**Comment by xiaofan-luan** [comment]
hi @kubecutle 
the only thing you need to do is unify your vector.
it would be exact same as faiss.normalize_L2 code

**Comment by tawalke** [comment]
> hi @kubecutle the only thing you need to do is unify your vector. it would be exact same as faiss.normalize_L2 code

Can you share an example, please. I'm having the same exact issue

**Comment by kubecutle** [comment]
My issue is a non issue. I used vectors from OpenAI and they are already normalized. That means I can just use IP without doing any additional work. But if you need to normalize your vector, what I understand is that you have to do that before you upload thevector data into milvus.

Say you have a vector [x,y].

1) Compute the norm of your vector : norm=sqrt(x**2+y**2)
2) Divide x and y by norm. That gives you [x/norm,y/norm]

That's your normalized vector you push to milvus. And using MetricType.IP gives you cosine similarity.
