### ISSUE TITLE
[Not consistent with official documentation]listBulkInsertTasks() CollectionName NULL check

### ISSUE THREAD

**Issue by fall-nebula** [milvus-io/milvus-sdk-java#469]
In official documentation said List all tasks Parameter [collection_name ] is optional. And said "Leave the value empty if you want to list all tasks recorded by Milvus root coords".
[Docs](https://milvus.io/docs/bulk_insert.md#List-all-tasks)
But in `io.milvus.client.AbstractMilvusGrpcClient#listBulkInsertTasks` used:
```java
            ListImportTasksRequest listImportTasksRequest = ListImportTasksRequest.newBuilder()
                    .setCollectionName(requestParam.getCollectionName())
                    .setLimit(requestParam.getLimit())
                    .build();
```
And `io.milvus.grpc.ListImportTasksRequest.Builder#setCollectionName` don't allow value is null.
```java
    public ListImportTasksRequest.Builder setCollectionName(
            java.lang.String value) {
        if (value == null) {
            throw new NullPointerException();
        }

        collectionName_ = value;
        onChanged();
        return this;
    }
```

**Comment by yhmo** [comment]
Fixed by this pr, which will be released in v2.2.9
