### ISSUE TITLE
How to build an index on scalar fields by java

### ISSUE THREAD

**Issue by xuhaixing** [milvus-io/milvus-sdk-java#471]
```
        MilvusConfig.milvusServiceClient.createIndex(
            CreateIndexParam.newBuilder()
                .withIndexName("idx_book_name")
                .withCollectionName("book")
                .withFieldName("book_name")
//                .withIndexType(IndexType.AUTOINDEX)
//                .withMetricType(MetricType.INVALID)
                .build()
        );
```
this is not success

**Comment by xuhaixing** [comment]
``
        MilvusConfig.milvusServiceClient.createIndex(
            CreateIndexParam.newBuilder()
                .withIndexName("idx_book_name")
                .withCollectionName("book")
                .withFieldName("book_name")
//                .withIndexType(IndexType.AUTOINDEX)
//                .withMetricType(MetricType.INVALID)
                .build()
        );
``

**Comment by xuhaixing** [comment]
```
        MilvusConfig.milvusServiceClient.createIndex(
            CreateIndexParam.newBuilder()
                .withIndexName("idx_book_name")
                .withCollectionName("book")
                .withFieldName("book_name")
//                .withIndexType(IndexType.AUTOINDEX)
//                .withMetricType(MetricType.INVALID)
                .build()
        );
```

**Comment by yhmo** [comment]
In 2.2.8, SORT index type is added for integer/float datatype

MilvusConfig.milvusServiceClient.createIndex(
            CreateIndexParam.newBuilder()
                .withCollectionName("test")
                .withFieldName("int_field")
                .withIndexType(IndexType.SORT)
                .build()
        );
