### ISSUE TITLE
log4j2.xml 问题

### ISSUE THREAD

**Issue by sxf20220704** [milvus-io/milvus-sdk-java#474]
log4j2.xml 这个配置文件会影响我项目中的日志打印，这个能不能加个开关，我可以关掉这个日志配置？

**Comment by yhmo** [comment]
后续版本会加这个开关

**Comment by yhmo** [comment]
https://github.com/milvus-io/milvus-sdk-java/pull/543/files
这个pr提供了一个设置，可以设置日志打印的级别，在2.2.8版本里
```
MilvusServiceClient client = new MilvusServiceClient()
client.setLogLevel(LogLevel.Error)
```
