### ISSUE TITLE
服务端开启TLS,Java SDK 不支持通过证书调用? python支持

### ISSUE THREAD

**Issue by herozeng** [milvus-io/milvus-sdk-java#489]

**Comment by xiaofan-luan** [comment]
python也没有支持，除非证书发布过，否则都得给证书

**Comment by herozeng** [comment]
想问下JAVA SDK 怎么给证书，没有参数可以传

**Comment by cliu701** [comment]
I also find Java SDK not able to pass tls cert.
Here is python code that support give tls cert: https://github.com/milvus-io/pymilvus/blob/3be5aba72c50c181c1f2cfbe73f5652323e2aa7c/pymilvus/orm/connections.py#L261

**Comment by zirota** [comment]
You can pass your TLS certs via the `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` environment variable.

**Comment by yhmo** [comment]
Support TLS:
https://github.com/milvus-io/milvus-sdk-java/pull/559
