### ISSUE TITLE
[ParatitionKey]-- InsertRequest failed(InsertParam without paratition param): not support manually specifying the partition names if partition key mode is used

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus-sdk-java#505]
@Test(description = "Insert data into collection with partition key")
    public void insertData(){
        List<InsertParam.Field> fields = CommonFunction.generateDataWithPartitionKey(10000);
        // insert
        R<MutationResult> insert = milvusClient.insert(InsertParam.newBuilder()
                .withFields(fields)
                .withCollectionName(collection)
                .build());
        Assert.assertEquals(insert.getStatus().intValue(),0);
    }

**Comment by yhmo** [comment]
fixed in 2.2.8
