### ISSUE TITLE
[partition key]--Insert with partition name param need be  disabled in partition key mode

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus-sdk-java#510]
@Test(description = "Insert use partition name param in  Partition key mode")
    public void InsertWithPartitionName() {
        List<InsertParam.Field> fields = CommonFunction.generateDataWithPartitionKey(10000);
        // insert
        R<MutationResult> insert = milvusClient.insert(InsertParam.newBuilder()
                .withFields(fields)
                .withCollectionName(collection)
                .withPartitionName(CommonData.defaultPartitionField)
                .build());
        Assert.assertEquals(insert.getStatus().intValue(), 1);
    }

**Comment by yhmo** [comment]
Already fixed in v2.2.8
