### ISSUE TITLE
MilvusClient sometimes will return "You are not connected to Milvus server" after it being connected to server for a long time

### ISSUE THREAD

**Issue by shenchenguo** [milvus-io/milvus-sdk-java#56]
I have created a singleton instance of `MilvusClient` and connected to Milvus server already.
When there are no operations on `MilvusClient` for a long time, sometimes it will return "You are not connected to Milvus server" as `Response` message.
After review code, the GRPC create `Channel`:
>       channel =
>           ManagedChannelBuilder.forAddress(connectParam.getHost(), port)
>               .usePlaintext()
>               .maxInboundMessageSize(Integer.MAX_VALUE)
>               .build();
Can we solve the problem by adding keepalive settings？like:
>       channel =
>           ManagedChannelBuilder.forAddress(connectParam.getHost(), port)
>               .keepAliveTime(5, TimeUnit.MINUTES)
>               .keepAliveWithoutCalls(true)
>               .keepAliveTimeout(10, TimeUnit.MINUTES)
>               .idleTimeout(24, TimeUnit.HOURS)
>               .usePlaintext()
>               .maxInboundMessageSize(Integer.MAX_VALUE)
>               .build();

**Comment by youny626** [comment]
Hi, thanks for pointing out this issue! Not setting an idleTimeout was definitely an oversight. Users should be able to customize keep alive or idleTimeOut settings in `ConnnectParam`. I will fix it soon!

**Comment by youny626** [comment]
Done
