### ISSUE TITLE
the Index still exists after it has been deleted

### ISSUE THREAD

**Issue by shenchenguo** [milvus-io/milvus-sdk-java#58]
First, I create a `Index` on a table named "example", then delete the Index by calling dropIndex method.When I call the describeIndex method to make sure the index info was empty of the 'example' table, it will still return the index info that I created.

**Comment by youny626** [comment]
Hi, could you provide the `IndexType` of the`Index` you created and the `Index` returned by `describeIndex`? Also, which version of Milvus server did you use?
When you drop an index, the `IndexType` will be changed to `FLAT`. So `describeIndex` will still return an `Index`.
I just tested again and it seems okay.
![Screenshot from 2019-11-06 14-35-29](https://user-images.githubusercontent.com/9016120/68273940-bf281b00-00a2-11ea-85b2-75e6c9daa2fa.png)

**Comment by shenchenguo** [comment]
You are right.When I drop an index, the `IndexType` will be changed to `FLAT`.
I created `Index` and then describe it as this:
![create](https://user-images.githubusercontent.com/19384736/68275036-905f7400-00a5-11ea-9a2a-5142ed78a9ac.png)
then drop the `Index`:
![describe](https://user-images.githubusercontent.com/19384736/68275040-90f80a80-00a5-11ea-970f-564c9c5366cc.png)
then describe the index of table 'example' again:
![drop](https://user-images.githubusercontent.com/19384736/68275044-92c1ce00-00a5-11ea-970a-ea4d8a939130.png)
the version of Milvus server is 0.5.1
![server](https://user-images.githubusercontent.com/19384736/68275427-96098980-00a6-11ea-9755-e254b5b1c821.png)

**Comment by yhmo** [comment]
Let me explain this. Assume we have an empty table, its index type is default: FLAT. Then user insert 1M vectors into the table. The vectors are stored as 'raw data', one by one write into 'raw file'. If user perform a search action, milvus will do brute-force search. And then user create index SQ8, milvus will generate 'index file' for each 'raw file', the table index type changes to: SQ8, all search action become index-search(much faster than brute-force search).   Now, user drop index, milvus will delete all 'index file', the table index type changes to FALT, but the 'raw file' is sill kept, all search action become brute-force search again.
