### ISSUE TITLE
insert method can pass in the same vectorId

### ISSUE THREAD

**Issue by shenchenguo** [milvus-io/milvus-sdk-java#59]
`InsertResponse insert(InsertParam insertParam)` method is called whether at the same time or different times, it can pass in ` java.lang.Long` type `java.util.List` composed with the same vectorId.

**Comment by yhmo** [comment]
Hi shenchenguo,
    This issue you encountered is 'as designed'. The insert api allow user specify id for each vector, but Milvus doesn't verify id internally since the validation could be very expensive. For instance, user create a table and already insert 1 billion vectors into the table, then he insert 1 vectors again and specify id for it. To verify the id, we need to compare the id to one billion times, this is unacceptable.
    So user must ensure the id he input is unique for each vector. Otherwise, milvus also can automatically generate unique id for each vector if he input an empty id list.

Thanks

**Comment by shenchenguo** [comment]
OK, thank you for your help.

**Comment by hdoer** [comment]
> Hi shenchenguo,
> This issue you encountered is 'as designed'. The insert api allow user specify id for each vector, but Milvus doesn't verify id internally since the validation could be very expensive. For instance, user create a table and already inserted 1 billion vectors into the table, then he insert 1 vectors again and specify id for it. To verify the id, we need to compare the id one billion times, it is unacceptable.
> So user must ensure the id he input is unique for each vector. Otherwise, milvus also can automatically generate unique id(base on timestamp) for each vector if he input an empty id list.
> 
> Thanks

Unbelievable, it is not usual practice.
