### ISSUE TITLE
can't find collection

### ISSUE THREAD

**Issue by yyy1sss** [milvus-io/milvus-sdk-java#591]
milvus specified the Database when creating the Collection. When milvus-SDk-Java was used to query the collection, the database could not be specified. As a result, the collection can't be found

**Comment by yyy1sss** [comment]
public static class Builder {
        private String collectionName;
        private final List<String> partitionNames = Lists.newArrayList();
        private final List<String> outFields = new ArrayList<>();
        private String expr = "";
        private Long travelTimestamp = 0L;
        private Long gracefulTime = 5000L;
        private Long guaranteeTimestamp = Constant.GUARANTEE_EVENTUALLY_TS;
        private ConsistencyLevelEnum consistencyLevel = null;
        private Long offset = 0L;
        private Long limit = 0L;
        private Boolean ignoreGrowing = Boolean.FALSE;

        private Builder() {
        }
}

**Comment by yhmo** [comment]
The recommended way to specify database in Java sdk is:
`ConnectParam.Builder.withDatabaseName(String databaseName)`

Specify the database name when you set up the connection. If you didn't set the database name, a "default" name will be used.

**Comment by yyy1sss** [comment]
final MultiConnectParam multiConnectParam = MultiConnectParam.newBuilder()
                .withDatabaseName("udesk_kep")
                .withHosts(serverAddresses).build();
        milvusMultiServiceClient = new MilvusMultiServiceClient(multiConnectParam);

**This is the connection I created。Using milvus-sdk-java version 2.2.12。
Below is the log that I searched after loading the data。**


LoadCollectionParam(databaseName=udesk_kep, collectionName=udesk_kep_analysis_file9c7714af_3a294, syncLoad=true, syncLoadWaitingInterval=500, syncLoadWaitingTimeout=60, replicaNumber=1, refresh=false)
MilvusService::disposeStatus:successR{status=0, data=RpcStatus{msg='Success'}}

QueryParam{collectionName='udesk_kep_analysis_file9c7714af_3a294', partitionNames='[]', outFields=[id, app_id, region, business_type, business_id, file_id, effectivity, create_user_id, create_time, update_user_id, update_time, embedding], expr='app_id == "9c7714af_3a294" && file_id in [22]', consistencyLevel='null', offset=0, limit=0, ignoreGrowing='false'}
QueryRequest failed:code: UnexpectedError, reason: code: CollectionNotExists, reason: can't find collection: udesk_kep_analysis_file9c7714af_3a294

**Comment by yyy1sss** [comment]
@yhmo

**Comment by yhmo** [comment]
Confirmed, this is a bug. The database name was not passed to the ConnectParam for each client in this method:
https://github.com/milvus-io/milvus-sdk-java/blob/f1d1fbcc00804f4c297cb7cdc027edffb1a012ff/src/main/java/io/milvus/client/MilvusMultiServiceClient.java#L82

Will fix it in the next minor version.

**Comment by yhmo** [comment]
The pr #638 #639 #640 fix this bug.
