### ISSUE TITLE
Add withDatabaseName argument to SelectGrantForRole method

### ISSUE THREAD

**Issue by charleskakumanu** [milvus-io/milvus-sdk-java#601]
Please add a feature to provide database name to SelectGrantForRole method in java SDK. Cannot make fresh connections every time, especially when we have huge number of databases.

**Comment by yhmo** [comment]
Sorry, the milvus proto doesn't support passing a database name for the SelectGrant interface, not able to pass it from sdk.

**Comment by charleskakumanu** [comment]
Just need to get **privileges that a user has** and **what databases they have access to**. Currently, SelectGrantForRole is working for “default” database only. Can we get privileges and database access details for all users (if they have access to different databases and we don’t know which database they have access to)?
