### ISSUE TITLE
Can JAVA SDK support the count(*) API like pymilvus?

### ISSUE THREAD

**Issue by weiZhenkun** [milvus-io/milvus-sdk-java#614]
https://milvus.io/docs/query.md#Count-entities

![image](https://github.com/milvus-io/milvus-sdk-java/assets/27683687/ea486d0b-75c4-4d22-ad61-d4a26a4f3b8d)

**Comment by xiaofan-luan** [comment]
you can try to set output fields as count(*), it should be handled as well

**Comment by xiaofan-luan** [comment]
@AnthonyTsu1984 
Any special reason we don't support other language in the document?

**Comment by weiZhenkun** [comment]
> @AnthonyTsu1984 Any special reason we don't support other language in the document?

Thanks, I will try.

**Comment by yhmo** [comment]
count(*) is passed by string, no need to change the code, already supported.

```
QueryParam test = QueryParam.newBuilder()
                .withCollectionName(COLLECTION_NAME)
                .withExpr("count(*)")
                .build();
```
