### ISSUE TITLE
Can we release milvus-java-sdk with COSINE?

### ISSUE THREAD

**Issue by weiZhenkun** [milvus-io/milvus-sdk-java#619]
As https://github.com/milvus-io/milvus-sdk-java/pull/616 has merged to master, can we release a version?

**Comment by xiaofan-luan** [comment]
we've working on this I guess

**Comment by xiaofan-luan** [comment]
or you can do it, should be pretty simple

**Comment by yhmo** [comment]
Java sdk v2.3.1 has been released last night. This version supports COSINE.
https://github.com/milvus-io/milvus-sdk-java/releases/tag/v2.3.1

**Comment by weiZhenkun** [comment]
Thanks
