### ISSUE TITLE
Can't set loglevel when use MilvusMultiServiceClient

### ISSUE THREAD

**Issue by LeePui** [milvus-io/milvus-sdk-java#623]
We use milvus cluster mode.
In Java SDK, we use `MilvusMultiServiceClient`. There is not method `setLogLevel` in `MilvusMultiServiceClient` . `setLogLevel` is a method in `MilvusServiceClient`.
`setLogLevel` --> `MilvusServiceClient` --> `clusterFactory` --> `MilvusMultiServiceClient`.
`MilvusMultiServiceClient` can't  get `clusterFactory`  or `MilvusServiceClient`

**Comment by LeePui** [comment]
![image](https://github.com/milvus-io/milvus-sdk-java/assets/14257862/0b1cc0c6-dc59-4ef9-aced-2932dc99b4d2)
log has a high CPU usage

**Comment by yhmo** [comment]
Will add a method for MilvusMultiServiceClient to set log level in the next minor version.

**Comment by yhmo** [comment]
The pr #634 #635 #637 fix this issue.
