### ISSUE TITLE
OpenAI embedding store Milvus Error

### ISSUE THREAD

**Issue by caopengan** [milvus-io/milvus-sdk-java#624]
When I use the embedding api of openai to store the embedding to milvus, there will always be an error. I suspect it is caused by the size of data transfer. However, I have looked at the grpc setting and it should be called Problem.
image
![image](https://github.com/milvus-io/milvus-sdk-java/assets/12568699/db759a4e-0397-46a7-9ee0-acb91f57d0d4)

rpc setting：

image
![image](https://github.com/milvus-io/milvus-sdk-java/assets/12568699/d3dee9d8-9972-4b9a-9aa0-9bc89000f36c)

But I did not transfer objects that exceeded this limit

**Comment by xiaofan-luan** [comment]
> When I use the embedding api of openai to store the embedding to milvus, there will always be an error. I suspect it is caused by the size of data transfer. However, I have looked at the grpc setting and it should be called Problem. image ![image](https://user-images.githubusercontent.com/12568699/266975209-db759a4e-0397-46a7-9ee0-acb91f57d0d4.png)
> 
> rpc setting：
> 
> image ![image](https://user-images.githubusercontent.com/12568699/266975259-d3dee9d8-9972-4b9a-9aa0-9bc89000f36c.png)
> 
> But I did not transfer objects that exceeded this limit

did you try to ping milvus port see if network accessible?

**Comment by yhmo** [comment]
Possible reason: the server is in TLS mode, but the client is not.

Try using the ConnectParam.Builder.withSecure(true) to build a connection with TLS.

**Comment by caopengan** [comment]
> > When I use the embedding api of openai to store the embedding to milvus, there will always be an error. I suspect it is caused by the size of data transfer. However, I have looked at the grpc setting and it should be called Problem. image ![image](https://user-images.githubusercontent.com/12568699/266975209-db759a4e-0397-46a7-9ee0-acb91f57d0d4.png)
> > rpc setting：
> > image ![image](https://user-images.githubusercontent.com/12568699/266975259-d3dee9d8-9972-4b9a-9aa0-9bc89000f36c.png)
> > But I did not transfer objects that exceeded this limit
> 
> did you try to ping milvus port see if network accessible?

When I create multiple collections at the same time, only the embedding using Openai will report an error, and other embedding can be used normally

**Comment by caopengan** [comment]
> Possible reason: the server is in TLS mode, but the client is not.
> 
> Try using the ConnectParam.Builder.withSecure(true) to build a connection with TLS.

e...,the server is not in TLS mode

**Comment by yhmo** [comment]
I read the source code of langchain4j, it is no problem with the class MilvusEmbeddingStore/MilvusEmbeddingStoreImpl.
There is a parameter "secure" in the constructor of MilvusEmbeddingStore class. What value did you pass to this parameter?
```
public MilvusEmbeddingStore(String host,
                                int port,
                                String databaseName,
                                String uri,
                                String token,
                                boolean secure,
                                String username,
                                String password,
                                MilvusCollectionDescription collectionDescription,
                                MilvusOperationsParams operationsParams)
```

**Comment by caopengan** [comment]
> I read the source code of langchain4j, it is no problem with the class MilvusEmbeddingStore/MilvusEmbeddingStoreImpl. There is a parameter "secure" in the constructor of MilvusEmbeddingStore class. What value did you pass to this parameter?
> 
> ```
> public MilvusEmbeddingStore(String host,
>                                 int port,
>                                 String databaseName,
>                                 String uri,
>                                 String token,
>                                 boolean secure,
>                                 String username,
>                                 String password,
>                                 MilvusCollectionDescription collectionDescription,
>                                 MilvusOperationsParams operationsParams)
> ```

Thank you, I have already fixed the problem, it was caused by the milvus version, I upgraded from milvus:v2.2.13 to Milv2.2.14, the problem is no longer, I think it is a bug in the old version

**Comment by caopengan** [comment]
thanks everybody
