### ISSUE TITLE
UNKNOWN: it's a deny api, fullMethod:/milvus.proto.milvus.MilvusService/CreatePartition

### ISSUE THREAD

**Issue by qingsongxi** [milvus-io/milvus-sdk-java#625]
采用SDK创建分区时，报错找不到这个API
<dependency>
    <groupId>io.milvus</groupId>
    <artifactId>milvus-sdk-java</artifactId>
    <version>2.2.9</version>
</dependency>

**Comment by yhmo** [comment]
If you are using this api on Zilliz cloud, it will return this error. The Zilliz cloud doesn't allow user to create partition currently.

**Comment by xiaofan-luan** [comment]
Partition feature will be supported on cloud end of Oct

**Comment by yhmo** [comment]
Denied by server side, not by sdk, close this issue
