### ISSUE TITLE
search with Consistency level, but the Proxy Debug log always shows Strong

### ISSUE THREAD

**Issue by bingbb47** [milvus-io/milvus-sdk-java#626]
Set Consistency level when search, we can see that different levels correspond to different lentancy.
But in Proxy Debug log, it shows Strong whatever level I set
<img width="1075" alt="image" src="https://github.com/milvus-io/milvus-sdk-java/assets/111261344/914272db-6276-4494-a3b4-76c113ba07e7">
I think this is very confusing for Debug

**Comment by bingbb47** [comment]
env:
Milvus 2.2.14; java sdk 2.2.13

**Comment by yhmo** [comment]
The consistency level can be set in two ways:
1. construction of a collection
        ```
CreateCollectionParam createParam = CreateCollectionParam.newBuilder()
                .withCollectionName(randomCollectionName)
                .withFieldTypes(fieldsSchema)
                .withConsistencyLevel(ConsistencyLevelEnum.STRONG)
                .build();
```

2. as a parameter of search()
```
SearchParam searchParam = SearchParam.newBuilder()
                .withCollectionName(randomCollectionName)
                .withMetricType(MetricType.L2)
                .withTopK(topK)
                .withVectors(targetVectors)
                .withVectorFieldName(field2Name)
                .withParams("{\"ef\":64}")
                .addOutField(field4Name)
                .withConsistencyLevel(ConsistencyLevelEnum.BOUNDED)
                .build();

        R<SearchResults> searchR = client.search(searchParam);
```

The consistency level defined in the collection constructor is "default level". 
The level defined by the search parameter is "override level".
The log shows "[use_default_consistency=false] ["consistency level"=Strong]", it means the collection's default level is Strong, now you have specified the level in search parameter, so the use_default_consistency=false.

**Comment by bingbb47** [comment]
> The consistency level can be set in two places:
> 
> 1. constructor of a collection
> 
> ```
> CreateCollectionParam createParam = CreateCollectionParam.newBuilder()
>                 .withCollectionName(randomCollectionName)
>                 .withFieldTypes(fieldsSchema)
>                 .withConsistencyLevel(ConsistencyLevelEnum.STRONG)
>                 .build();
> ```
> 
> 2. as a parameter of search()
> 
> ```
>     SearchParam searchParam = SearchParam.newBuilder()
>                 .withCollectionName(randomCollectionName)
>                 .withMetricType(MetricType.L2)
>                 .withTopK(topK)
>                 .withVectors(targetVectors)
>                 .withVectorFieldName(field2Name)
>                 .withParams("{\"ef\":64}")
>                 .addOutField(field4Name)
>                 .withConsistencyLevel(ConsistencyLevelEnum.BOUNDED)
>                 .build();
> 
>         R<SearchResults> searchR = client.search(searchParam);
> ```
> 
> The consistency level defined in the collection constructor is "default level". The level defined by the search parameter is "override level". The log shows "[use_default_consistency=false] ["consistency level"=Strong]", it means the collection's default level is Strong, now you have specified the level in search parameter, so the use_default_consistency=false.


In my test, I hava set the consistency level as Bounded with java sdk, bug the log shows Strong; the same request in python sdk shows Bounded.

**Comment by yhmo** [comment]
Good catch! I have confirmed it is a bug of java sdk.
When calling search(), the consistency level is not passed to the server side, it uses the level defined by Collection constructor to search.

If the level is STRONG defined in Collection constructor, the log will show ["consistency level"=Strong], no matter what level is passed by the SearchParam.
If you didn't define level in Collection constructor, it will always use BOUNDED level to search.

**Comment by yhmo** [comment]
The pr #628 #629 #630 fix this issue.
