### ISSUE TITLE
some partitions [aaaa] of collection vvvv has been loaded into QueryNode, please release partitions firstly[LoadParameterMismatched]

### ISSUE THREAD

**Issue by zihao2981** [milvus-io/milvus-sdk-java#689]
load的提示这个问题，但是也查不到LoadParameterMismatched

**Comment by yhmo** [comment]
I didn't find this error message in milvus source code and java sdk source code. Which version of your milvus and sdk?

The message says some partitions of the collection have been loaded, not allow to call load_collection() at this moment. You should use release_partition() to release the partitions firstly and then load_collection().
