### ISSUE TITLE
can not create table

### ISSUE THREAD

**Issue by fallowu** [milvus-io/milvus-sdk-java#7]
milvus-server: milvusdb/milvus:latest
version:v0.4.0
config:

> 
![image](https://user-images.githubusercontent.com/3997050/66532475-1c7f8980-eb42-11e9-8c37-0b9425f53275.png)

change sleep time to 5000, 

>ConnectivityState connectivityState;
> connectivityState = channel.getState(true);
>  logInfo("Waiting to connect...");
> TimeUnit.MILLISECONDS.sleep(5000);
> connectivityState = channel.getState(false);
> if (connectivityState != ConnectivityState.READY) {
>logSevere("Connect failed! {0},connectivityState:{1}", connectParam.toString(), connectivityState);
> return new Response(Response.Status.CONNECT_FAILED);

 just run MilvusGrpcClientTest.createTable method, and the log will be:

> 信息: Connected successfully!
ConnectParam {host='192.168.1.100', port='19530'}
十月 10, 2019 9:32:01 上午 io.milvus.client.MilvusGrpcClient logSevere
严重: Create table failed
TableSchema = {tableName = ecqruakdag, dimension = 128, indexFileSize = 1024, metricType = L2}
error_code: ILLEGAL_TABLE_NAME
reason: "Invalid table name: "
十月 10, 2019 9:32:01 上午 io.milvus.client.MilvusGrpcClient logSevere
严重: dropTable RPC failed:
Status{code=INTERNAL, description=Did not read entire message, cause=null}
org.opentest4j.AssertionFailedError: 
Expected :true
Actual   :false

**Comment by fallowu** [comment]
but pymilvus simple_example.py is ok.
```python
# This program demos how to create a Milvus table, insert 20 vectors and get the table row count.
from milvus import Milvus, IndexType, MetricType

import random
import time

milvus = Milvus()

# Connect Milvus server.
# You may need to change HOST and PORT accordingly.
milvus.connect(host='localhost', port='19530')

# Table name is defined
table_name = 'demo_table_02'

# Create table: table name, vector dimension and index type
if not milvus.has_table(table_name):
    milvus.create_table({'table_name': table_name, 'dimension': 256, 'index_file_size': 1024, 'metric_type': MetricType.L2})

# Insert 20 256-dim-vectors into demo_table
vectors = [[random.random() for _ in range(256)] for _ in range(20)]
milvus.add_vectors(table_name=table_name, records=vectors)
time.sleep(1)

# Get table row count
_, result = milvus.get_table_row_count(table_name=table_name)
print('Table {}, row counts: {}'.format(table_name, result))
```

**Comment by youny626** [comment]
Hey, thanks for using Milvus! 
The Java SDK is still in development phase, it’s not compatible with the current Milvus version (0.4.0). It’s only compatible with Milvus 0.5.0, which will be released soon.
PyMilvus is compatible, so you can use it for now before the Java SDK is officially released. :D

**Comment by youny626** [comment]
FYI. Milvus 0.5.0 and the Java SDK is officially released~
