### ISSUE TITLE
[chore] update dependancy on grpc-netty

### ISSUE THREAD

**Issue by MarcusDunn** [milvus-io/milvus-sdk-java#703]
I'm not certain the exact chain of events - but updating my projects `grpc-netty` to `1.59` caused my tests to fail as `milvus-sdk-java` brings in `io.grpc:grpc-netty:1.46` (how exactly this broke the service loading is beyond me). I've currently got a gradle constraint to fix the problem - but would like to remove it, 1.46 is more than a year old.

**Comment by yhmo** [comment]
Milvus project and all the milvus sdk projects are using the same rpc proto, the proto is defined in a separate project: https://github.com/milvus-io/milvus-proto

The milvus project is Golang, the rpc interfaces are generated in the milvus-proto project by grpc v1.46: https://github.com/milvus-io/milvus-proto/blob/d32551f32ac11c796387b79030880558b48774e4/go-api/go.mod#L7

To avoid incompatible risk, all the sdk projects are using the same grpc version. In java sdk, the grpc version is also v1.46: https://github.com/milvus-io/milvus-sdk-java/blob/6bc4304e9fe5b69ff204b3abe67a2adf38a3c5b5/pom.xml#L67C3-L67C3

**Comment by tzolov** [comment]
<img width="736" alt="Screenshot 2023-11-22 at 16 43 39" src="https://github.com/milvus-io/milvus-sdk-java/assets/1351573/f9bb43f7-4368-4c2b-bbda-374877d43b1c">

**Comment by yhmo** [comment]
The https://github.com/milvus-io/milvus-sdk-java/pull/713 and https://github.com/milvus-io/milvus-sdk-java/pull/713 has upgraded the grpc to 1.59.1

**Comment by yhmo** [comment]
2.3.4 was released with the fix
