### ISSUE TITLE
The latest (milvus-sdk-java:2.3.3) is flagged with several security vulnerabilities, all due to an outdated GRPC stack (1.46.0)

### ISSUE THREAD

**Issue by tzolov** [milvus-io/milvus-sdk-java#704]
[milvus-sdk-java:2.3.3](https://mvnrepository.com/artifact/io.milvus/milvus-sdk-java/2.3.3)

<img width="736" alt="Screenshot 2023-11-22 at 16 43 39" src="https://github.com/milvus-io/milvus-sdk-java/assets/1351573/fd4ed63d-850f-4920-be77-a2665e6d6faa">

**Comment by tzolov** [comment]
Related to https://github.com/milvus-io/milvus-sdk-java/issues/703

**Comment by yhmo** [comment]
The https://github.com/milvus-io/milvus-sdk-java/pull/713 and https://github.com/milvus-io/milvus-sdk-java/pull/713 has upgraded the grpc to 1.59.1

**Comment by tzolov** [comment]
Thanks for the update @yhmo !
May you know when this is going to be released?

**Comment by yhmo** [comment]
2.3.4 already released
