### ISSUE TITLE
loadCollection and releaseCollection ，Can resource isolation be ensured when calling multiple threads simultaneously

### ISSUE THREAD

**Issue by lironghai** [milvus-io/milvus-sdk-java#728]
Can resource isolation be ensured when calling multiple threads simultaneously？

for example：
 A thread:
    singletonMilvusClient.loadCollection("aaa");
    singletonMilvusClient.search("aaa",...);
 B thread:
    singletonMilvusClient.loadCollection("aaa");

 A thread:
    singletonMilvusClient.releaseCollection ("aaa");

 B thread:
     singletonMilvusClient.search("aaa",...);

**Comment by yhmo** [comment]
A thread:
singletonMilvusClient.loadCollection("aaa");
singletonMilvusClient.search("aaa",...);
B thread:
singletonMilvusClient.loadCollection("aaa");

loadCollection() interface is idempotent on the server side, it is no problem to call it from multiple clients.
In Java sdk, all the RPC interfaces are thread-safe, no problem to call the same interface from multiple threads.
