### ISSUE TITLE
Create index parameters problem for scalar

### ISSUE THREAD

**Issue by shopenhe** [milvus-io/milvus-sdk-java#733]
The doc said: `To build an index on scalar fields, you do not need to set any index parameters.`  at https://milvus.io/docs/build_scalar_index.md

But, the Java SDK will check indexType required:

https://github.com/milvus-io/milvus-sdk-java/blob/d2adef1f2083057b4a3c2d394a35b213b672caf7/src/main/java/io/milvus/param/index/CreateIndexParam.java#L241

It's not good that I must set the right indexType for different dataType, so I advice that Java SDK could set the default indexType.

**Comment by yhmo** [comment]
No need to set index parameters, but you need to specify an index type.

The CreateIndexParam has these methods:
withIndexType()
withMetricType()
withExtraParam()

For scalar field, you don't need to call withMetricType() and withExtraParam(), but you need to call withIndexType() to specify index type.
For VARCHAR field, the index type is TRIE.
For Int/Float field, the index type is STL_SORT.



JAVA example:
https://github.com/milvus-io/milvus-sdk-java/blob/5af81f8fb6baf9522f7469ed9b2fbad349deb508/examples/main/java/io/milvus/SimpleExample.java#L93

**Comment by yhmo** [comment]
A commit has been merged to set the default index type: https://github.com/milvus-io/milvus-sdk-java/pull/742
The next version will contain this commit.

**Comment by shopenhe** [comment]
Got, THX
