### ISSUE TITLE
How to set default values for scalar fields

### ISSUE THREAD

**Issue by lironghai** [milvus-io/milvus-sdk-java#739]
set default values for scalar fields

**Comment by xiaofan-luan** [comment]
currently milvus didn't support default value  or null for now.

@weiliu1031 @lixin is working on it, it should be done on March 2024

**Comment by lironghai** [comment]
> 目前 milvus 暂不支持默认值或 null。
> 
> @weiliu1031 @lixin正在研究中，预计将于 2024 年 3 月完成

Thank you.
