### ISSUE TITLE
java sdk exception: how to use manual vectorId when insert vectors

### ISSUE THREAD

**Issue by VincentChen525** [milvus-io/milvus-sdk-java#81]
When I insert vectors with vector IDs using Java SDK, there is a exception:
InsertResponse {Response {code = ILLEGAL_VECTOR_ID, message = "Table vector IDs are auto-generated. All vectors of this table must use auto-generated IDs."}, returned 0 vector ids}
however, python edition can use manual vector IDs to insert

**Comment by youny626** [comment]
That was because you had previously inserted to the same table without providing vector ids. A table can only have auto-generated ids or user-defined ids, not both.
