### ISSUE TITLE
Cannot resolve io.milvus:milvus-sdk-java:2.4.0

### ISSUE THREAD

**Issue by 131452099900** [milvus-io/milvus-sdk-java#813]
maven拉取最新包失败，之前用的是2.3.2

**Comment by yhmo** [comment]
master 分支还没有正式发布2.4.0，也就是说目前java sdk还没有可以用在milvus 2.4.0上的版本。

2.3分支才是对应milvus 2.3版本的，你切到2.3分支就没问题

**Comment by yhmo** [comment]
Java SDK v2.4.0 has already been released, close this issue.
