### ISSUE TITLE
Add sparse float vector support

### ISSUE THREAD

**Issue by zhengbuqian** [milvus-io/milvus-sdk-java#827]
Milvus 2.4 has added beta support to sparse float vector to allow efficient storing, indexing and searching of such vectors. The main targeted use case is to support learned sparse models such as SPLADE and statistics based methods such as BM25. 

We need to add sparse float vector to Java SDK as well. See: https://github.com/milvus-io/milvus/issues/29419#issuecomment-2024887328 for more details.

Thanks a lot for the efforts!

**Comment by yhmo** [comment]
Already done in v2.4.0
