### ISSUE TITLE
Is it possibile to define a scalar field of type array of Integers?

### ISSUE THREAD

**Issue by PiercarloSlavazza** [milvus-io/milvus-sdk-java#842]
Using Mivus 2.3.3 (where int_array is supported if I have understood properly) and Java Milvus sdk 2.3.5.

Code is something like:

```dart
FieldType fieldTypeJudges = FieldType.newBuilder()
                .withName(fieldName)
                .withDataType(DataType.<it seems that array of integer is missing>)
                .build();
```

**Comment by yhmo** [comment]
To define an Array field:
```
FieldType fieldTypeJudges = FieldType.newBuilder()
                .withDataType(DataType.Array)
                .withElementType(DataType.Int32)
                .withName(fieldName)
                .withMaxCapacity(500)
                .build()
```

withDataType(DataType.Array) ---------------------- this field is an Array field
withElementType(DataType.Int32) ------------------ elmenet type of the array is int32
withMaxCapacity(500) --------------------------------- length of the array is no more than 500

**Comment by PiercarloSlavazza** [comment]
Thank you! I overlooked DataType.Array.

What about insertion? If I have a List<Integer> it's just `new InsertParam.Field(keyOfArrayField, myListOfIntegers)`?

**Comment by yhmo** [comment]
For DataType.Array + ElementType.Int32/Int16/Int8, the valid input is List<Integer> or List<Short>
For DataType.Array + ElementType.Float32, the valid input is List<Float>
For DataType.Array + ElementType.Float64, the valid input is List<Double>
For DataType.Array + ElementType.Varchar, the valid input is List<String>
For DataType.Array + ElementType.JSON, the valid input is List<JSONObject>
etc.

This is a test case to show how to insert data for Array field:
https://github.com/milvus-io/milvus-sdk-java/blob/ab46ffcfdb17521998086f5fed7f76837677bbec/src/test/java/io/milvus/client/MilvusClientDockerTest.java#L245

The interval convert method is here:
https://github.com/milvus-io/milvus-sdk-java/blob/ab46ffcfdb17521998086f5fed7f76837677bbec/src/main/java/io/milvus/param/ParamUtils.java#L898
It converts a List according to the ElementType of the Array.

**Comment by PiercarloSlavazza** [comment]
Crystal clear - thank you.
