### ISSUE TITLE
cannot find  milvus-sdk-java 2.4.0 in the Maven Repository

### ISSUE THREAD

**Issue by liangzzong** [milvus-io/milvus-sdk-java#845]
![IMG20240409-154748862](https://github.com/milvus-io/milvus-sdk-java/assets/37288684/45ecb6f1-132c-4f79-845a-44904621a10e)
![IMG20240409-154748861](https://github.com/milvus-io/milvus-sdk-java/assets/37288684/d8c00830-1703-4d5c-8551-028bd4d1c99b)

**Comment by yhmo** [comment]
Milvus-sdk-java 2.4.0 is still in testing.

**Comment by liangzzong** [comment]
ok thank you

**Comment by PiercarloSlavazza** [comment]
> Milvus-sdk-java 2.4.0 is still in testing.

Hi, any plan for the release?
I am asking because the 2.4.0 will contain - in my understanding - the iterators feature, which happens to be super useful to me at the present moment…

Thank you.

**Comment by yhmo** [comment]
@PiercarloSlavazza 
The iterator feature was committed last Friday: https://github.com/milvus-io/milvus-sdk-java/pull/851, the testing work just begun, still needs a few days to verify.

**Comment by yhmo** [comment]
Java SDK v2.4.0 has been released, close this issue.
