### ISSUE TITLE
SDK 2.3.5 brings a vulnerable version of hadoop libraries

### ISSUE THREAD

**Issue by orpiske** [milvus-io/milvus-sdk-java#852]
Hey folks, thanks for your great work on this! 

Recently, we added a component for Milvus on Apache Camel 4.5.0, [released just a few weeks ago](https://camel.apache.org/blog/2024/03/camel45-whatsnew/). 

Yesterday we tried bumping the SDK dependency from 2.3.4, but we noticed that [2.3.5 brings a older version](https://mvnrepository.com/artifact/io.milvus/milvus-sdk-java/2.3.5) of the Hadoop client (2.7.0) that is [vulnerable to multiple CVEs](https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-client/2.7.0) - I believe this came as part of the [bulk writer feature](https://github.com/milvus-io/milvus-sdk-java/pull/804/files). 

Please, would it be possible to upgrade to a newer version of Hadoop that is not vulnerable?

**Comment by lentitude2tk** [comment]
Hello, I have noticed this issue. I will confirm the impact of the upgrade to ensure there is no conflict with existing dependencies.

**Comment by lentitude2tk** [comment]
Has been done:
https://github.com/milvus-io/milvus-sdk-java/pull/854
https://github.com/milvus-io/milvus-sdk-java/pull/853

**Comment by lentitude2tk** [comment]
Milvus SDK Java versions 2.3.6 & 2.4.0 have been released, you can upgrade to the corresponding versions. Thank you for your usage.
