### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by onestow** [milvus-io/milvus-sdk-java#877]
My JDK version is 1.8, milvus-sdk-java version is 2.4.0, when I run `SearchResultsWrapper.getIDScore`, and I got the exception:
```
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at io.milvus.response.FieldDataWrapper.getFieldData(FieldDataWrapper.java:248)
	at io.milvus.response.FieldDataWrapper.valueByIdx(FieldDataWrapper.java:351)
	at io.milvus.response.SearchResultsWrapper.getIDScore(SearchResultsWrapper.java:207)
	at com.tom.MilvusTest.myTest(MilvusTest.java:190)
	at com.tom.MilvusTest.main(MilvusTest.java:114)
```
how to solve it?

**Comment by onestow** [comment]
jdk21 is normal
jdk8 is not support?

**Comment by xiaofan-luan** [comment]
https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/

**Comment by xiaofan-luan** [comment]
this is a java compilation bug need to be fixed.

@onestow would you mind fix that?

**Comment by onestow** [comment]
I'm sorry, but I haven't had time for anything else lately  v_v

**Comment by yhmo** [comment]
Java SDK is compiled by openjdk 11 with language level 8. Seems this is an issue of ByteBuffer. If it cannot run under jdk 1.8, try use jdk 11 instead.
I need to install 1.8 to test the issue first, I am not sure is any quick solution there.

**Comment by xiaofan-luan** [comment]
check the link

...
<properties>
  <maven.compiler.release>8</maven.compiler.release>
</properties>
...

**Comment by yhmo** [comment]
maven.compiler.release doesn't resolve this issue.

I tested on my local.
- compile sdk with openjdk 1.8 and language level 8
build client with openjdk 1.8 and language level 8, the ByteBuffer works fine
build client with openjdk 11 and language level 8, the ByteBuffer works fine

- compile sdk with openjdk 11 and language level 8
build client with openjdk 1.8 and language level 8, get NoSuchMethod error of ByteBuffer such as rewind()/position()
build client with openjdk 11 and language level 8, get NoSuchMethod error of ByteBuffer such as rewind()/position()

**Comment by yhmo** [comment]
From v2.4.2, Java SDK is built by OpenJDK 1.8, close this issue.
