### ISSUE TITLE
当milvus服务出现问题时，我怎么来让我的客户端进行重连呢？

### ISSUE THREAD

**Issue by zhupengfly** [milvus-io/milvus-sdk-java#89]
我现在的策略是采用的定时任务定时去检测milvus服务，当我检测到我的服务异常的时候，我就去断开客户端现在的连接，然后再去创建新的连接。但是我发现我在压测数据入库时，如果把把milvus重启，虽然能重新创建新的连接，但是数据不再入库了，请问这是什么原因呢？
`    @Scheduled(initialDelay = 1000L, fixedDelay = 1000L)
    public void reconnect() {
        boolean serverStatus = milvusDataSource.getServerStatus();
        if (!serverStatus) {
            log.info("Disconnect Milvus.");
            boolean disconnect = milvusDataSource.disconnect();
            if (disconnect) {
                log.info("Reconnect Milvus.");
                milvusDataSource.connect(host, port);
            }
        }
    }`

**Comment by sahuang** [comment]
你好，请问server那边你有重启吗？我看了你的代码，如果只是判断disconnect就重连，server不restart是没有用的。

此外在connectParam里你可以设置client连接keep alive，这样更方便。

还有问题欢迎提问，谢谢

**Comment by zhupengfly** [comment]
嗯，服务那边做了心跳检测的，当服务检测多次异常后，会对milvus服务进行重启操作。但是存在一个问题，就是发现在进行数据入库的时候，如果milvus服务重启了，那么数据将不再入库，我不知道是否是因为client没有设置keep alive。我会把这个设置上后再次尝试下。
