### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3

### ISSUE THREAD

**Issue by xiqiuyimeng** [milvus-io/milvus-sdk-java#90]
![image](https://user-images.githubusercontent.com/34128138/80373792-2e4f3100-88c8-11ea-96f3-788a711e1dce.png)
我在服务器上搭建了milvus0.8的cpu服务，访问正常。
下载了0.7的jar包依赖，
![image](https://user-images.githubusercontent.com/34128138/80374162-d06f1900-88c8-11ea-9ed6-cf1fa08149ba.png)
这个请问是什么问题？希望官方大大帮忙看看

**Comment by sahuang** [comment]
你好,你发的那两张图好像失效了, 能更新下吗?

**Comment by sahuang** [comment]
你好,我本地试了下没有出现这个错误,这个应该是dependency mismatch问题,从报错能看出这个错误就是java的类加载器 ClassLoader 找不到 com/google/protobuf/GeneratedMessageV3. 

个人觉得很可能是jar多重包含导致的路径查找错误, 您要不试一下把protobuf-java jar重新添加到工程里,clean一下再build试试看? 这个跟milvus的java包依赖应该是没关系的.

**Comment by xiqiuyimeng** [comment]
> 你好,我本地试了下没有出现这个错误,这个应该是dependency mismatch问题,从报错能看出这个错误就是java的类加载器 ClassLoader 找不到 com/google/protobuf/GeneratedMessageV3.
> 
> 个人觉得很可能是jar多重包含导致的路径查找错误, 您要不试一下把protobuf-java jar重新添加到工程里,clean一下再build试试看? 这个跟milvus的java包依赖应该是没关系的.

您好，我的问题是，我要使用milvus的java客户端sdk，然后根据官网下载maven依赖，然后按着官网源码中的例子进行测试，发现报错，我的项目中并没有这个google的依赖包

**Comment by xiqiuyimeng** [comment]
> 你好,我本地试了下没有出现这个错误,这个应该是dependency mismatch问题,从报错能看出这个错误就是java的类加载器 ClassLoader 找不到 com/google/protobuf/GeneratedMessageV3.
> 
> 个人觉得很可能是jar多重包含导致的路径查找错误, 您要不试一下把protobuf-java jar重新添加到工程里,clean一下再build试试看? 这个跟milvus的java包依赖应该是没关系的.

**Comment by luyi666** [comment]
mvn dependency:tree -Dincludes=com.google.protobuf看看
