### ISSUE TITLE
数组字段支持索引吗？ 没有索引查询起来很慢，怎么搞

### ISSUE THREAD

**Issue by ghost** [milvus-io/milvus-sdk-java#902]

**Comment by xiaofan-luan** [comment]
what is the expression you a re using?
we are working on indexing array already

**Comment by shopenhe** [comment]
> what is the expression you a re using? we are working on indexing array already

`array_contains_any `

**Comment by xiaofan-luan** [comment]
it is under development already

**Comment by shopenhe** [comment]
@xiaofan-luan 目前进度如何？如果已发版本请通知我，谢谢

**Comment by yhmo** [comment]
Milvus v2.4.15中已支持数组索引： https://milvus.io/docs/array_data_type.md#Index-array-field
