### ISSUE TITLE
[v2]-Use the milvusClientV2.describeCollection interface to view the vector of bf16/float16/sparse vector type. The vectorFieldName in the return value is empty.

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus-sdk-java#927]
java-sdk-version : master-v2
correct return：
![img_v3_02bp_1c268830-b5b2-4908-911c-1534c503255g](https://github.com/milvus-io/milvus-sdk-java/assets/103410837/e66c17e3-41c5-486a-8d81-7e16f4daac2d)
Currently returned is empty：
![img_v3_02bp_0da63d73-75c0-496f-aefc-9fca5728b9eg](https://github.com/milvus-io/milvus-sdk-java/assets/103410837/9faf7153-8ebe-43ff-aed9-6998d2c71983)

**Comment by yhmo** [comment]
Fixed: https://github.com/milvus-io/milvus-sdk-java/pull/928
