### ISSUE TITLE
Does milvus support search data by json field condition?

### ISSUE THREAD

**Issue by king1302217** [milvus-io/milvus-sdk-java#930]
Data in milvus has two fields, eg: id: string, meta: json.     meta eg: {"name":"sam", "age":18}
Does milvus support search data by json field condition?

eg:
  SearchParam.Builder builder = SearchParam.newBuilder()
                    .withCollectionName(collectionName)
                    .withMetricType(metricType)
                    .withTopK(searchLimit)
                    .withVectors(vectors)
                    .withVectorFieldName(vectorField)
                    .withExpr("**meta.name == 'sam'**");
R<SearchResults> search = milvusServiceClient.search(builder.build());

**Comment by xiaofan-luan** [comment]
it should be meta["name"]="sam"

**Comment by xiaofan-luan** [comment]
see https://milvus.io/docs/use-json-fields.md
