### ISSUE TITLE
milvus-sdk-java 2.3.5版本后，引入了hadoop-client依赖，其中slf4j-reload4j-1.7.36.jar与logback-classic-1.2.12.jar存在冲突，有好的解决方案吗？

### ISSUE THREAD

**Issue by yu-you** [milvus-io/milvus-sdk-java#935]
存在相同的org/slf4j/impl/StaticLoggerBinder.class
是否可以排除hadoop-client依赖？

**Comment by yhmo** [comment]
是不是这样的warning?
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/yhmo/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.17.1/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/yhmo/.m2/repository/org/slf4j/slf4j-reload4j/1.7.36/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
```

我暂时也没有好的解决方法。hadoop引入是因为那个BulkWriter工具需要用到

**Comment by yu-you** [comment]
> 是不是这样的warning?
> 
> ```
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/home/yhmo/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.17.1/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/home/yhmo/.m2/repository/org/slf4j/slf4j-reload4j/1.7.36/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
> ```
> 
> 我暂时也没有好的解决方法。hadoop引入是因为那个BulkWriter工具需要用到

log4j-slf4j-impl-2.17.1.jar与slf4j-reload4j-1.7.36.jar都是milvus-sdk-java引入进来的，项目的日志记录是用的logback。目前是排除了log4j-slf4j-impl和hadoop-client依赖，不清楚排除hadoop-client依赖后会影响到哪些功能？

**Comment by yhmo** [comment]
https://github.com/milvus-io/milvus-sdk-java/pull/937
这个pr应该能解决这个问题
