### ISSUE TITLE
java sdk中dataType为DataType.Bool的字段无法使用STL_SORT索引，但是文档中是可以支持

### ISSUE THREAD

**Issue by wangsheng23576** [milvus-io/milvus-sdk-java#943]
在Java SDK中对DataType.Bool的字段，设置索引类型为STL_SORT时会报错，但是在文档中（https://milvus.io/docs/index-scalar-fields.md）是支持的。
<img width="853" alt="image" src="https://github.com/milvus-io/milvus-sdk-java/assets/173866301/39686f1c-917d-43be-b376-938655c63482">

**Comment by xiaofan-luan** [comment]
/assign @longjiquan 
please help on check

**Comment by longjiquan** [comment]
Please help to modify the document, @AnthonyTsu1984 
/unassign
/assign @AnthonyTsu1984

**Comment by yhmo** [comment]
文档已更新，STL_SORT不支持bool
https://milvus.io/docs/index-scalar-fields.md#Index-Scalar-Fields
