### ISSUE TITLE
Java SDK中使用MilvusClientV2的search(SearchReq request)方法返回的结果中score字段名变成了distance

### ISSUE THREAD

**Issue by wangsheng23576** [milvus-io/milvus-sdk-java#944]
Java SDK中使用MilvusClientV2的search(SearchReq request)方法返回的结果如下：
{
	"searchResults": [
		[{
			"distance": 1.4093276,
			"id": "UUID202405301234567891",
			"entity": {}
		}, {
			"distance": 0.99021345,
			"id": "UUID202405301234567895",
			"entity": {}
		}, {
			"distance": 0.85199434,
			"id": "UUID202405301234567892",
			"entity": {}
		}, {
			"distance": 0.79723436,
			"id": "UUID202405301234567896",
			"entity": {}
		}, {
			"distance": 0.59287345,
			"id": "UUID202405301234567893",
			"entity": {}
		}, {
			"distance": 0.4527678,
			"id": "UUID202405301234567894",
			"entity": {}
		}]
	]
}
但是在文档和attu的返回结果如下：
<img width="411" alt="image" src="https://github.com/milvus-io/milvus-sdk-java/assets/173866301/1001c997-d976-4536-8e35-7903887e1903">
代码返回的“distance”字段名应该是“score”。

**Comment by wangsheng23576** [comment]
在文档中（https://milvus.io/docs/single-vector-search.md）的示例描述如下：
<img width="372" alt="image" src="https://github.com/milvus-io/milvus-sdk-java/assets/173866301/7b331094-489b-4aa7-9ca4-001b32e9b22e">

**Comment by yhmo** [comment]
这名字其实不重要，不管是score还是distance其实都不是好名字。

**Comment by wangsheng23576** [comment]
> 这名字其实不重要，不管是score还是distance其实都不是好名字。

好的，不过distance较大的值排在前面，给我的第一影响是越不相似，越排在前面。可能score更符合人的思维惯性

**Comment by wangsheng23576** [comment]
> 这名字其实不重要，不管是score还是distance其实都不是好名字。

明白了，不同的metric获得的值会有区别。
