### ISSUE TITLE
使用milvus java sdk的QueryIterator出现报错:id > \Q123456\, error: line 1:12 token recognition error at: '\'

### ISSUE THREAD

**Issue by feriki** [milvus-io/milvus-sdk-java#964]
看起来是io.milvus.orm.iterator.QueryIterator#setupNextExpr方法导致的，使用的milvus-sdk-java版本是2.3.6，如图
![21](https://github.com/milvus-io/milvus-sdk-java/assets/29164761/13676549-7060-44b8-b405-b19798cf5f00)

**Comment by xiaofan-luan** [comment]
public static String incrementString(String str) {
        if (str == null || str.isEmpty()) {
            throw new IllegalArgumentException("Input string cannot be null or empty");
        }

        // Convert the string to a character array for easier manipulation
        char[] chars = str.toCharArray();
        boolean carry = true;
        int index = chars.length - 1;

        while (carry && index >= 0) {
            if (chars[index] == 255) {
                chars[index] = 0; // Reset to the starting character, could also be 'a'
                index--;
            } else {
                chars[index]++;
                carry = false;
            }
        }

        // If carry is still true, it means we have overflowed beyond the most significant character
        if (carry) {
            // You can decide what to do in this case, here we prepend a new character
            return "1" + new String(chars);
        }

        return new String(chars);
    }

**Comment by xiaofan-luan** [comment]
I thought we can not just append something to string.
@MrPresent-Han please help on it

**Comment by xiaofan-luan** [comment]
public static byte[] incrementBytes(byte[] value) {
        if (value == null || value.length == 0) {
            throw new IllegalArgumentException("Input byte array cannot be null or empty");
        }

        byte[] newValue = value.clone();
        boolean carry = true;
        int index = newValue.length - 1;

        while (carry && index >= 0) {
            if (newValue[index] == (byte) 0xFF) {
                newValue[index] = 0;
                index--;
            } else {
                newValue[index]++;
                carry = false;
            }
        }

        // If carry is still true, this means we have overflowed beyond the most significant byte
        if (carry) {
            byte[] extendedValue = new byte[newValue.length + 1];
            System.arraycopy(newValue, 0, extendedValue, 1, newValue.length);
            extendedValue[0] = 1; // Add a new leading byte
            return extendedValue;
        }

        return newValue;
    }

**Comment by yhmo** [comment]
python也有类似的问题，处理varchar中带有 双引号，单引号，转义符 的情况都有些问题。目前queryIterator/searchIterator无法处理。在setupNextExpr方法中使用String.replace的方式把双引号和单引号转义，可以部分修复这个问题。但是包含转义符的字符串我觉得似乎无解。

而query()/search()处理起来需要特别的写法。比如某个Varchar字段，插入如下字符串:
"\Q1234"
如果想用query过滤，得这么写 collection.query(expr="\\\\Q1234")

"\"Q1234"
如果想用query过滤，得这么写 collection.query(expr="\\"Q1234")

"\'Q1234"
如果想用query过滤，得这么写 collection.query(expr="\'Q1234")
