### ISSUE TITLE
版本对照表有点问题

### ISSUE THREAD

**Issue by xsnull** [milvus-io/milvus-sdk-java#978]
我的 milvus 版本 2.3.3，java-sdk 是 2.3.6
![IYZQUDCnwn](https://github.com/milvus-io/milvus-sdk-java/assets/100367743/c121ac55-88eb-4aa0-ab3e-8e66c4179d6f)
参考了这个版本对照表，在加了用户密码之后一直连接不上。最后切换为 2.3.3 解决<br/>`Method threw 'java.lang.UnsupportedOperationException' exception. Cannot evaluate io.milvus.grpc.ClientInfo.toString()`

**Comment by yhmo** [comment]
我刚试了一下，milvus v2.3.3，把milvus.yaml中的security.authorizationEnabled改为true，然后分别用Java SDK的v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7都跑了一下，用examples中的SimpleExample，使用默认root:Milvus连接
```
MilvusServiceClient milvusClient = new MilvusServiceClient(ConnectParam.newBuilder()
                .withHost("localhost")
                .withPort(19530)
                .withAuthorization("root","Milvus")
                .build());
```
这几个SDK版本都能正常跑完SimpleExample.

**Comment by xsnull** [comment]
我本地试了一下版本确实没问题，但是在线上项目就是不行，很奇怪，不知道是不是有一些冲突啥的。
