### ISSUE TITLE
Not Able to upsert document into collection with type Float16Vector.

### ISSUE THREAD

**Issue by daxesh020500** [milvus-io/milvus-sdk-java#983]
I have created one collection in Milvus v2.4.4, and using Milvus SDK v2.4.1

When I try to upsert the document with io.milvus.v2.client.MilvusClientV2 upsert method, it used DataUtil.convertGrpcUpsertRequest and then the call goes through the checkFieldData of io.milvus.v2.utils.DataUtils

However, if we see the cases in the switch statement 
<img width="970" alt="image" src="https://github.com/milvus-io/milvus-sdk-java/assets/43899470/09025038-69d9-4932-8d9a-374139799e2f">
**It does not have Float16Vector**, Which leads to throwing this exception
 ```
default:
                throw new IllegalResponseException("Unsupported data type returned by FieldData");

```

Is it done intentionally to not use the Float16Vector or it is missed somehow?

**Comment by yhmo** [comment]
v2.4.1 was released on May 11th, the MilvusClientV2 doesn't support Float16Vector/BFloat16Vector/SparseVector. The old MilvusServiceClient supports Float16Vector/BFloat16Vector/SparseVector.

This pr #909 is merged on May 29th, support Float16Vector/BFloat16Vector/SparseVector for MilvusClientV2.
In the next minor version v2.4.2, both MilvusServiceClient/MilvusClientV2 can support all the vector types.
v2.4.2 will be released in this week.

**Comment by daxesh020500** [comment]
Thanks for the information.
