### ISSUE TITLE
No found insertIds, please check your requests

### ISSUE THREAD

**Issue by mmahao** [milvus-io/milvus-sdk-java#984]
java的sdk，版本2.2.13

![image](https://github.com/milvus-io/milvus-sdk-java/assets/34231454/5cfcbbcd-4f0b-41be-b0cd-160116fa21c8)
![image](https://github.com/milvus-io/milvus-sdk-java/assets/34231454/3a85c274-f59a-43c5-aa3c-9d1a9de22e33)
![image](https://github.com/milvus-io/milvus-sdk-java/assets/34231454/9ef46aed-5317-449b-ad24-2a4cf006ef6d)

这块调用的时候，有点问题
1.当向量库里面有数据的时候，数据是删掉了，但是报错：No found insertIds, please check your requests
2.当向量库里面没有数据的时候，返回的delCount也是1，也是报错：No found insertIds, please check your requests

这个问题，不知道是不是因为bug引起的，如果有什么好的解决办法，请提供一下，多谢🙏🙏🙏

**Comment by mmahao** [comment]
这块的话因为我是delete操作，并不是insert，所以return R.success(DeleteResponse.builder().deleteIds(resultWrapper.getInsertIDs()).build());是不是调用错方法了。

**Comment by mmahao** [comment]
![image](https://github.com/milvus-io/milvus-sdk-java/assets/34231454/5ac7633e-96c4-4264-9578-db6c25c442cd)

**Comment by yhmo** [comment]
MilvusClient里有两个delete接口：
R<MutationResult> delete(@NonNull DeleteParam requestParam)
R<DeleteResponse> delete(DeleteIdsParam requestParam)

上面那个是原生的，下面那个是包了一层的所谓高级接口。
实际上你调用这个高级的delete时，内部那个原生的delete是成功返回了的。而当这个高级接口包装一个DeleteResponse返回的时候，是通过MutationResultWrapper.getInsertIDs()想拿id，实际上原生的delete接口并不返回被删除的id，所以这里就会抛出那个"No found insertIds, please check your requests"
https://github.com/milvus-io/milvus-sdk-java/blob/3e8c58f7b2a3e314a8f3b8644ef3cb4b2bedf418/src/main/java/io/milvus/response/MutationResultWrapper.java#L69

我的建议是用原生的delete 接口。要知道的是，delete是个异步操作，当你发送一堆id过去之后，server端只是把delete request推送到pulsar就返回，所以客户端delete接口返回时并不知道到底有多少数据会被删除。所以只要那个R<MutationResult>返回SUCCESS就可以认为delete请求以被server端接受，后面会异步处理。
```
         R<MutationResult> deleteR = milvusClient.delete(DeleteParam.newBuilder()
                .withCollectionName(COLLECTION_NAME)
                .withExpr(ID_FIELD + "==1")
                .build());
        if (deleteR.getStatus() != R.Status.Success.getCode()) {
            throw new RuntimeException("Failed to delete! Error: " + insertRet.getMessage());
        }
```

**Comment by mmahao** [comment]
还有个问题，向量库里面没有数据的时候，最后返回的删除count还是1，这个不确定是bug还是原本的设计。

我这边准备直接手动调用`String expr = VectorUtils.convertPksExpr(requestParam.getPrimaryIds(), wrapper);`最后就不调用`resultWrapper.getInsertIDs()`了，这样应该就ok了

**Comment by mmahao** [comment]
解决了，放弃`String expr = VectorUtils.convertPksExpr(requestParam.getPrimaryIds(), wrapper);`

用：`String expr = "id in " + primaryIds;

        DeleteParam deleteIdsParam = DeleteParam.newBuilder()
                .withCollectionName(collectionName)
                .withExpr(expr)
                .build();

        R<MutationResult> deleteResponseR = milvusServiceClient.delete(deleteIdsParam);`

**Comment by yhmo** [comment]
delete()返回的那个delete count没有什么用，server端只是简单地把要删除的id统计一下返回给客户端。实际真正删除了多少，在返回的时候是不知道的，因为是异步执行。

**Comment by xiaofan-luan** [comment]
> java的sdk，版本2.2.13
> 
> ![image](https://private-user-images.githubusercontent.com/34231454/347232772-5cfcbbcd-4f0b-41be-b0cd-160116fa21c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDYzMjQsIm5iZiI6MTcyMTA0NjAyNCwicGF0aCI6Ii8zNDIzMTQ1NC8zNDcyMzI3NzItNWNmY2JiY2QtNGYwYi00MWJlLWIwY2QtMTYwMTE2ZmEyMWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEyMjAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhY2VjMGU5OGI5MDFhN2Q1MmM2ZGRlZjBlNGJhMmRkOWRmY2EyZDU5NjYxMzQyNWM1MTNhNWUzNjVhNjQzNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3jhbbOyRFX1F1AFcOaQl-s1cpKx7Jgz8jLyWG95fcdc) ![image](https://private-user-images.githubusercontent.com/34231454/347232890-3a85c274-f59a-43c5-aa3c-9d1a9de22e33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDYzMjQsIm5iZiI6MTcyMTA0NjAyNCwicGF0aCI6Ii8zNDIzMTQ1NC8zNDcyMzI4OTAtM2E4NWMyNzQtZjU5YS00M2M1LWFhM2MtOWQxYTlkZTIyZTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEyMjAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMTQzMTY5NWQwZWU2Nzc4MWIyZjU4OGI0MWE0YTlmMGFjN2ZhMDQ5YTgwMGIyYzUyNGNjYTg1YzRhODQwOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4IzBmfZ224fj2T3d605DEZ4MqfNQcccG_AjlPrEOoS0) ![image](https://private-user-images.githubusercontent.com/34231454/347233021-9ef46aed-5317-449b-ad24-2a4cf006ef6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDYzMjQsIm5iZiI6MTcyMTA0NjAyNCwicGF0aCI6Ii8zNDIzMTQ1NC8zNDcyMzMwMjEtOWVmNDZhZWQtNTMxNy00NDliLWFkMjQtMmE0Y2YwMDZlZjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEyMjAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiM2JiZTg3MjI3ZmZlZGVlMmFjNTBhMTdjNzU4ODVkNzIwMGFjMzg0ODY1ZmFkMWRlYjMyYTQzOWU0N2ZjOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yov9eI-hoWlG61TgL5KqSvXE_4sPVznwx9b9ejVgQfA)
> 
> 这块调用的时候，有点问题 1.当向量库里面有数据的时候，数据是删掉了，但是报错：No found insertIds, please check your requests 2.当向量库里面没有数据的时候，返回的delCount也是1，也是报错：No found insertIds, please check your requests
> 
> 这个问题，不知道是不是因为bug引起的，如果有什么好的解决办法，请提供一下，多谢🙏🙏🙏

目前都是deleteByID，为啥还要getID呢？Milvus本身也不知道删除了哪些ID的，你GetInsertID自然就会报错。
